# -*- coding: utf-8 -*-
"""Icon/logo tests: generator, committed assets, PE embedding.

The art is generated by ``tools/make_icon.py`` rather than checked in as an
unexplained blob, so it can be tested like code:

* the generator is deterministic (same bytes on every run);
* the committed ``assets/`` files are exactly what the generator produces, so a
  hand edit cannot silently drift away from the script;
* the ``.ico`` really is a multi-resolution icon (Windows picks 16 px in the
  taskbar and 256 px in Explorer, so all of them must be present and parseable);
* small sizes stay legible: the geometry is asserted to keep the jewel gold area
  inside a sane range, so a parameter change that turns 16 px into a blob or an
  empty square fails here rather than in a user's taskbar.
"""

from __future__ import annotations

import struct
import unittest
import zlib
from pathlib import Path

from tools import check_exe_icon, make_icon

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ASSETS = PROJECT_ROOT / "assets"
DIST_EXE = PROJECT_ROOT / "dist" / "Nioh3EquipmentAffixEditor.exe"


def decode_png(data: bytes) -> tuple[int, int, bytes]:
    """Decode a PNG we generated (8-bit RGBA, filter 0) into raw pixels."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise AssertionError("不是 PNG")
    offset, width, height, payload = 8, 0, 0, b""
    while offset < len(data):
        length, tag = struct.unpack_from(">I4s", data, offset)
        chunk = data[offset + 8:offset + 8 + length]
        if tag == b"IHDR":
            width, height, depth, color, _, _, _ = struct.unpack(">IIBBBBB", chunk)
            assert (depth, color) == (8, 6), "预期 8 位 RGBA"
        elif tag == b"IDAT":
            payload += chunk
        offset += 12 + length
    raw = zlib.decompress(payload)
    stride = width * 4
    assert len(raw) == (stride + 1) * height, "扫描线长度不符"
    rows = bytearray()
    for row in range(height):
        assert raw[row * (stride + 1)] == 0, "只支持 filter 0"
        rows += raw[row * (stride + 1) + 1:(row + 1) * (stride + 1)]
    return width, height, bytes(rows)


def pixel(pixels: bytes, width: int, x: int, y: int) -> tuple[int, int, int, int]:
    index = (y * width + x) * 4
    return tuple(pixels[index:index + 4])  # type: ignore[return-value]


class GeneratorTests(unittest.TestCase):
    def test_rendering_is_deterministic(self) -> None:
        self.assertEqual(make_icon.render(32), make_icon.render(32))

    def test_render_size_and_alpha(self) -> None:
        for size in (16, 32, 64):
            pixels = make_icon.render(size)
            self.assertEqual(len(pixels), size * size * 4)
            self.assertTrue(any(pixels[index + 3] for index in range(0, len(pixels), 4)),
                            "图标全透明")

    def test_icon_covers_every_declared_size(self) -> None:
        data = make_icon.ico_bytes()
        reserved, image_type, count = struct.unpack_from("<HHH", data, 0)
        self.assertEqual((reserved, image_type), (0, 1))
        self.assertEqual(count, len(make_icon.ICON_SIZES))
        sizes = [entry[0] for entry in check_exe_icon.read_ico_entries(
            _write_temp_ico(data))]
        self.assertEqual(sizes, list(make_icon.ICON_SIZES))

    def test_icon_entries_are_valid_images(self) -> None:
        """Every entry must be a self-describing image of the declared size."""
        entries = _read_entries(make_icon.ico_bytes())
        self.assertEqual([size for size, _blob_size, _blob in entries],
                         list(make_icon.ICON_SIZES))
        for size, blob_size, blob in entries:
            with self.subTest(size=size):
                self.assertEqual(len(blob), blob_size)
                if blob.startswith(b"\x89PNG"):
                    width, height, _ = decode_png(blob)
                    self.assertEqual((width, height), (size, size))
                    self.assertIn(size, make_icon.PNG_ENTRY_SIZES)
                else:  # BITMAPINFOHEADER + bottom-up pixels + AND mask
                    header_size, width, doubled_height, planes, bits = \
                        struct.unpack_from("<IiiHH", blob, 0)
                    self.assertEqual(header_size, 40)
                    self.assertEqual((width, doubled_height), (size, size * 2))
                    self.assertEqual((planes, bits), (1, 32))
                    mask_stride = ((size + 31) // 32) * 4
                    self.assertEqual(len(blob),
                                     40 + size * size * 4 + mask_stride * size)
                    self.assertNotIn(size, make_icon.PNG_ENTRY_SIZES)

    def test_bmp_entry_round_trips_exactly(self) -> None:
        """Decode the DIB back (BGRA, bottom-up) and compare with the raster."""
        for size in (16, 32):
            with self.subTest(size=size):
                rgba = make_icon.render(size)
                blob = make_icon.bmp_entry(size, rgba)
                decoded = bytearray()
                for row in range(size - 1, -1, -1):  # DIB is bottom-up
                    line = 40 + row * size * 4
                    for column in range(size):
                        blue, green, red, alpha = blob[line + column * 4:
                                                       line + column * 4 + 4]
                        decoded += bytes((red, green, blue, alpha))
                self.assertEqual(bytes(decoded), rgba)

    def test_bmp_entry_ends_with_the_and_mask(self) -> None:
        size = 24
        blob = make_icon.bmp_entry(size, make_icon.render(size))
        mask_stride = ((size + 31) // 32) * 4
        self.assertEqual(len(blob), 40 + size * size * 4 + mask_stride * size)
        self.assertEqual(blob[40 + size * size * 4:], bytes(mask_stride * size))

    def test_small_sizes_keep_the_jewel_visible(self) -> None:
        """A geometry change must not turn 16 px into a blob or an empty chip."""
        for size in (16, 24, 32):
            pixels = make_icon.render(size)
            total = size * size
            gold = dark = transparent = 0
            for index in range(0, len(pixels), 4):
                red, green, blue, alpha = pixels[index:index + 4]
                if alpha < 128:
                    transparent += 1
                elif red > 150 and green > 110 and blue < 140:
                    gold += 1
                elif red < 90 and green < 90 and blue < 110:
                    dark += 1
            self.assertGreater(gold / total, 0.15, f"{size}px 的金色过少")
            self.assertLess(gold / total, 0.60, f"{size}px 的金色过多")
            self.assertGreater(dark / total, 0.10, f"{size}px 的背景过少")
            self.assertLess(transparent / total, 0.25, f"{size}px 的透明区过多")

    def test_the_cord_hole_appears_only_at_large_sizes(self) -> None:
        small = make_icon._parameters(16)
        large = make_icon._parameters(256)
        self.assertEqual(small["hole_radius"], 0.0)
        self.assertGreater(large["hole_radius"], 0.0)

    def test_tangency_makes_a_tapered_tail(self) -> None:
        """|head - bite| must stay below R - r, i.e. the tail tapers to a point."""
        for size in (16, 32, 256):
            params = make_icon._parameters(size)
            gap = params["radius"] - params["bite_radius"]
            centre_gap = ((params["bite_x"] - params["head_x"]) ** 2
                          + (params["bite_y"] - params["head_y"]) ** 2) ** 0.5
            self.assertLess(centre_gap, gap, f"{size}px 的咬合圆不再内切")

    def test_logo_files_are_square_pngs(self) -> None:
        for name, size in make_icon.LOGO_FILES.items():
            with self.subTest(name=name):
                width, height, _ = decode_png((ASSETS / name).read_bytes())
                self.assertEqual((width, height), (size, size))

    def test_logo_is_transparent_outside_the_rounded_chip(self) -> None:
        width, height, pixels = decode_png((ASSETS / "logo.png").read_bytes())
        self.assertEqual(pixel(pixels, width, 0, 0)[3], 0, "圆角外应透明")
        self.assertEqual(pixel(pixels, width, width - 1, 0)[3], 0)
        centre = pixel(pixels, width, width // 2, height // 2)
        self.assertEqual(centre[3], 255, "中心应不透明")

    def test_logo_centre_is_ink_and_the_jewel_is_gold(self) -> None:
        width, height, pixels = decode_png((ASSETS / "logo.png").read_bytes())
        # The jewel's fat head sits up and right of centre; the middle of the
        # canvas is the dark void inside the curl.
        void = pixel(pixels, width, width // 2, height // 2)
        self.assertLess(max(void[:3]), 90, "勾玉内圈应为深墨色")
        head = pixel(pixels, width, int(width * 0.70), int(height * 0.30))
        self.assertGreater(head[0], 150, "勾玉头部应为金色")
        self.assertGreater(head[1], 120)


class CommittedAssetsTests(unittest.TestCase):
    def test_committed_assets_match_the_generator(self) -> None:
        self.assertEqual(make_icon.check_assets(), [])

    def test_every_logo_size_is_shipped(self) -> None:
        for name in make_icon.LOGO_FILES:
            self.assertTrue((ASSETS / name).is_file(), name)
        self.assertTrue((ASSETS / make_icon.ICON_NAME).is_file())

    def test_assets_directory_documents_itself(self) -> None:
        readme = (ASSETS / "README.md").read_text(encoding="utf-8")
        self.assertIn("tools/make_icon.py", readme)
        self.assertIn("勾玉", readme)
        # Provenance matters: state that this is not game art.
        self.assertIn("不是《仁王3》的游戏素材", readme)

    def test_check_mode_reports_a_modified_asset(self) -> None:
        import tempfile

        with tempfile.TemporaryDirectory(prefix="nioh3-icon-") as temp:
            target = Path(temp)
            make_icon.write_assets(target)
            self.assertEqual(make_icon.check_assets(target), [])
            (target / make_icon.ICON_NAME).write_bytes(b"not an icon")
            problems = make_icon.check_assets(target)
        self.assertEqual(len(problems), 1)
        self.assertIn("不一致", problems[0])

    def test_missing_asset_is_reported(self) -> None:
        import tempfile

        with tempfile.TemporaryDirectory(prefix="nioh3-icon-") as temp:
            problems = make_icon.check_assets(Path(temp))
        self.assertEqual(len(problems), len(make_icon.LOGO_FILES) + 1)
        self.assertTrue(all("缺少" in problem for problem in problems))


class PathsTests(unittest.TestCase):
    def test_icon_and_logo_paths_sit_in_assets(self) -> None:
        from nioh3_equipment_affix_editor import paths

        self.assertEqual(paths.icon_path().name, "app.ico")
        self.assertEqual(paths.icon_path().parent.name, "assets")
        self.assertEqual(paths.logo_path(32).name, "logo-32.png")
        self.assertEqual(paths.logo_path(64).name, "logo-64.png")
        # Unusual sizes fall back to the large logo instead of failing.
        self.assertEqual(paths.logo_path(48).name, paths.LOGO_NAME)

    def test_assets_is_a_resource_directory(self) -> None:
        from nioh3_equipment_affix_editor import paths

        self.assertIn("assets", paths.RESOURCE_DIRECTORIES)
        for size in paths.LOGO_SIZES:
            self.assertTrue((ASSETS / f"logo-{size}.png").is_file())


class BuiltExecutableTests(unittest.TestCase):
    """Only runs when a *current* built exe is present.

    A ``dist/`` exe older than ``assets/`` legitimately carries the previous
    artwork; ``build.ps1`` re-checks the freshly built exe with
    ``tools/check_exe_icon.py`` before it is shipped, so the assertion here is
    skipped instead of failing on a stale artifact.
    """

    def setUp(self) -> None:
        if not DIST_EXE.is_file():
            self.skipTest("dist/Nioh3EquipmentAffixEditor.exe 不存在")
        for asset in ASSETS.iterdir():
            if asset.is_file() and asset.stat().st_mtime > DIST_EXE.stat().st_mtime:
                self.skipTest(
                    f"dist 中的 exe 早于 {asset.name}；构建时会用 "
                    "tools/check_exe_icon.py 重新校验")

    def test_exe_carries_every_icon_size(self) -> None:
        report = check_exe_icon.inspect(DIST_EXE, ASSETS / make_icon.ICON_NAME)
        self.assertEqual(report["sizes"], sorted(make_icon.ICON_SIZES))
        self.assertEqual(report["mismatched_sizes"], [],
                         "dist 中的 exe 图标与当前 assets/ 不一致")
        self.assertEqual(report["identical_images"], report["expected_images"])

class GroupIconParserTests(unittest.TestCase):
    def test_reads_sizes_including_256(self) -> None:
        blob = struct.pack("<HHH", 0, 1, 2)
        blob += struct.pack("<BBBBHHIH", 16, 16, 0, 0, 1, 32, 100, 1)
        blob += struct.pack("<BBBBHHIH", 0, 0, 0, 0, 1, 32, 200, 2)  # 0 means 256
        self.assertEqual(check_exe_icon.icon_sizes_from_group(blob), [16, 256])

    def test_rejects_a_non_icon_resource(self) -> None:
        blob = struct.pack("<HHH", 0, 2, 0)
        with self.assertRaises(check_exe_icon.PeError):
            check_exe_icon.icon_sizes_from_group(blob)

    def test_rejects_a_file_without_pe_signature(self) -> None:
        with self.assertRaises(check_exe_icon.PeError):
            check_exe_icon._sections(b"not a pe file at all")


def _write_temp_ico(data: bytes) -> Path:
    import tempfile

    handle = tempfile.NamedTemporaryFile(suffix=".ico", delete=False)
    handle.write(data)
    handle.close()
    path = Path(handle.name)
    import atexit

    atexit.register(path.unlink, missing_ok=True)
    return path


def _read_entries(data: bytes) -> list[tuple[int, int, bytes]]:
    return [(size, blob_size, blob)
            for size, blob_size, blob in check_exe_icon.read_ico_entries(
                _write_temp_ico(data))]


if __name__ == "__main__":
    unittest.main()
