"""Version and build information for Nioh 3 Equipment Affix Editor.

Four facts are always reported, in this order:

1. ``commit``   -- the **last 8 characters** of the git commit id.
2. ``built_from`` / ``crypto_exe`` -- where this build came from: the project
   root and the crypto executable path at build time.  The user-visible banner
   reports the *run-time* counterparts (see ``version_lines``) and only mentions
   the build-time root when the two differ.
3. ``built_at`` -- the local build timestamp (ISO-8601 with UTC offset).
4. ``language`` -- the Python implementation/runtime the build targets.

Two sources are consulted, in this order:

* ``nioh3_equipment_affix_editor/_buildinfo.py`` -- generated by
  ``tools/make_build_info.py`` (called from ``build.ps1``).  This is what a
  packaged/distributed copy reports, since it carries frozen values.
* Live git interrogation of the source tree -- used when running from a
  checkout that has not been built; every unknown field degrades to
  ``"unknown"`` instead of raising, because version display must never break
  the application.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

from . import paths

__all__ = [
    "BUILD_SCHEMA",
    "DEFAULT_CRYPTO_EXE",
    "PROJECT_ROOT",
    "UNKNOWN",
    "BuildInfo",
    "commit_short",
    "short_commit",
    "version_banner",
    "version_info",
    "version_lines",
    "version_title",
    "__version__",
]

__version__ = "0.1.0"

BUILD_SCHEMA = "nioh3-accessory-editor-build/v1"
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CRYPTO_EXE = PROJECT_ROOT / "bin" / "Nioh_Savefile_decrypt.exe"
UNKNOWN = "unknown"
SHORT_COMMIT_LENGTH = 8

#: How long each user-visible line of the banner may be when generated.
_BANNER_WIDTH = 78

_CACHE: "BuildInfo | None" = None


def short_commit(commit: str | None) -> str:
    """Return the LAST ``SHORT_COMMIT_LENGTH`` characters of a commit id.

    Using the tail (not the usual git prefix) is a deliberate project
    convention, so the shortened id stays recognisable next to the full hash.
    Anything shorter is returned unchanged; ``None``/empty becomes ``unknown``.
    """
    if not commit:
        return UNKNOWN
    text = str(commit).strip()
    if not text:
        return UNKNOWN
    return text[-SHORT_COMMIT_LENGTH:]


# Public alias with the naming used by the build tooling.
commit_short = short_commit


@dataclass(frozen=True, slots=True)
class BuildInfo:
    """One immutable snapshot of version/build facts."""

    version: str
    commit: str
    commit_full: str
    branch: str
    dirty: bool
    built_at: str
    built_from: str
    crypto_exe: str
    crypto_exe_sha256: str
    language: str
    python_version: str
    source: str
    build_schema: str = BUILD_SCHEMA

    @property
    def commit_is_known(self) -> bool:
        return self.commit not in ("", UNKNOWN)

    @property
    def dirty_suffix(self) -> str:
        return " (工作区有未提交改动)" if self.dirty else ""

    def as_dict(self) -> dict[str, object]:
        return {
            "schema": self.build_schema,
            "component": "Nioh3EquipmentAffixEditor",
            "version": self.version,
            "commit": self.commit,
            "commit_full": self.commit_full,
            "branch": self.branch,
            "worktree_dirty": self.dirty,
            "built_at": self.built_at,
            "built_from": self.built_from,
            "crypto_exe": self.crypto_exe,
            "crypto_exe_sha256": self.crypto_exe_sha256,
            "language": self.language,
            "python_version": self.python_version,
            "info_source": self.source,
        }


# --------------------------------------------------------------------------
# Sources
# --------------------------------------------------------------------------

def _run_git(arguments: list[str]) -> str | None:
    """Run git in the project root, returning ``None`` when unavailable."""
    try:
        result = subprocess.run(
            ["git", *arguments],
            cwd=str(PROJECT_ROOT),
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def _git_info() -> dict[str, object] | None:
    commit_full = _run_git(["rev-parse", "HEAD"])
    if not commit_full:
        return None
    status = _run_git(["status", "--porcelain"])
    return {
        "commit_full": commit_full,
        "commit": short_commit(commit_full),
        "branch": _run_git(["rev-parse", "--abbrev-ref", "HEAD"]) or UNKNOWN,
        "dirty": bool(status) if status is not None else False,
    }


def _frozen_info() -> dict[str, object] | None:
    """Read the generated ``_buildinfo`` module when the build created one."""
    try:
        from . import _buildinfo  # type: ignore[attr-defined]  # noqa: PLC0415
    except ImportError:
        return None
    return {
        "version": getattr(_buildinfo, "VERSION", __version__),
        "commit": getattr(_buildinfo, "COMMIT", UNKNOWN),
        "commit_full": getattr(_buildinfo, "COMMIT_FULL", UNKNOWN),
        "branch": getattr(_buildinfo, "BRANCH", UNKNOWN),
        "dirty": bool(getattr(_buildinfo, "DIRTY", False)),
        "built_at": getattr(_buildinfo, "BUILT_AT", UNKNOWN),
        "built_from": getattr(_buildinfo, "BUILT_FROM", str(PROJECT_ROOT)),
        "crypto_exe": getattr(_buildinfo, "CRYPTO_EXE", str(DEFAULT_CRYPTO_EXE)),
        "crypto_exe_sha256": getattr(_buildinfo, "CRYPTO_EXE_SHA256", UNKNOWN),
        "language": getattr(_buildinfo, "LANGUAGE", UNKNOWN),
        "python_version": getattr(_buildinfo, "PYTHON_VERSION", UNKNOWN),
    }


def _runtime_language() -> str:
    import platform

    implementation = platform.python_implementation()
    version = platform.python_version()
    return f"{implementation} {version} (仅标准库 / stdlib only)"


def version_info(*, refresh: bool = False) -> BuildInfo:
    """Return the current build/version facts (cached)."""
    global _CACHE
    if _CACHE is not None and not refresh:
        return _CACHE

    frozen = _frozen_info()
    # A built executable has no checkout to interrogate (and no git binary in
    # reach), so its identity comes from the generated module only.
    live = None if paths.is_frozen() else _git_info()
    fields: dict[str, object] = {
        "version": __version__,
        "commit": UNKNOWN,
        "commit_full": UNKNOWN,
        "branch": UNKNOWN,
        "dirty": False,
        "built_at": UNKNOWN,
        "built_from": str(paths.application_root()),
        "crypto_exe": str(paths.default_crypto_exe()),
        "crypto_exe_sha256": UNKNOWN,
        "language": _runtime_language(),
        "python_version": _python_version(),
        "source": "fallback",
    }
    if live is not None:
        fields.update(live)
        fields["built_at"] = UNKNOWN  # a checkout has no build time
        fields["source"] = "git"
    if frozen is not None:
        fields.update({key: value for key, value in frozen.items()
                       if value not in (None, "")})
        fields["source"] = "build"
    if paths.is_frozen() and frozen is None:
        # Frozen without generated build info must still not claim to be a
        # checkout: report the executable itself as the source.
        fields["source"] = "frozen"
        fields["built_from"] = str(paths.application_root())

    _CACHE = BuildInfo(**fields)  # type: ignore[arg-type]
    return _CACHE


def _python_version() -> str:
    import platform

    return platform.python_version()


def reset_cache() -> None:
    """Drop the cached :class:`BuildInfo` (used by tests)."""
    global _CACHE
    _CACHE = None


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

def _take(text: str, budget: int, *, from_start: bool) -> str:
    """Longest prefix/suffix of ``text`` that fits ``budget`` display columns."""
    import unicodedata

    chars = text if from_start else reversed(text)
    kept: list[str] = []
    used = 0
    for char in chars:
        step = 2 if unicodedata.east_asian_width(char) in "WF" else 1
        if used + step > budget:
            break
        kept.append(char)
        used += step
    if not from_start:
        kept.reverse()
    return "".join(kept)


def _elide(text: str, width: int = _BANNER_WIDTH, *, enabled: bool = True) -> str:
    """Shorten ``text`` to ``width`` display columns, keeping the tail visible.

    The tail is what identifies the file (``...\\bin\\Nioh_Savefile_decrypt.exe``),
    so the abbreviation keeps a short head plus as much of the end as fits; a
    leading-only cut would hide exactly the part the reader needs.  ``enabled=False``
    returns the path untouched — the diagnostic ``BUILD-INFO.txt`` records full paths.
    """
    if not enabled or _display_width(text) <= width:
        return text
    budget = max(0, width - 3)
    head_budget = min(24, budget // 3)
    tail_budget = budget - head_budget
    return _take(text, head_budget, from_start=True) + "..." + _take(
        text, tail_budget, from_start=False)


def _display_width(text: str) -> int:
    """Terminal columns used by ``text`` (CJK/full-width characters count 2)."""
    import unicodedata

    return sum(2 if unicodedata.east_asian_width(char) in "WF" else 1
               for char in text)


def _pad_to(text: str, width: int) -> str:
    """Left-align ``text`` in a field ``width`` *display columns* wide."""
    return text + " " * max(0, width - _display_width(text))


def version_lines(
    info: BuildInfo | None = None,
    *,
    location: str | Path | None = None,
    crypto_exe: str | Path | None = None,
    elide: bool = True,
) -> tuple[str, ...]:
    """Human-readable version block, one entry per line.

    Field labels are padded by display width so the colons line up even in a
    mixed ASCII/CJK terminal.

    ``来源`` and ``加密组件`` are resolved **at run time**: the directory the
    running executable actually sits in and the crypto component it reads from
    there, so copying the exe elsewhere (or building on another machine) never
    prints a stale path.  The build-time project root is deliberately **not**
    shown anywhere: it names the machine the build ran on, which is of no use to
    whoever is running the editor.  It stays recorded in ``BUILD-INFO.txt`` for
    diagnosis.  ``location``/``crypto_exe`` override the resolution (tests only).
    """
    if info is None:
        info = version_info()
    label_width = 10
    built_at = info.built_at if info.built_at != UNKNOWN else "未构建（源码运行）"
    runtime_root = Path(location) if location is not None else paths.application_root()
    runtime_crypto = (Path(crypto_exe) if crypto_exe is not None
                      else paths.default_crypto_exe())
    lines = [
        f"Nioh 3 Equipment Affix Editor v{info.version}",
        f"{_pad_to('commit', label_width)}: {info.commit}{info.dirty_suffix}",
        f"{_pad_to('来源', label_width)}: {_elide(str(runtime_root), enabled=elide)}",
        f"{_pad_to('加密组件', label_width)}: {_elide(str(runtime_crypto), enabled=elide)}",
        f"{_pad_to('构建时间', label_width)}: {built_at}",
        f"{_pad_to('语言', label_width)}: {info.language}",
    ]
    return tuple(lines)


def version_banner(info: BuildInfo | None = None) -> str:
    """Multi-line banner used by ``--version``, the GUI and build reports."""
    return "\n".join(version_lines(info))


def version_title(info: BuildInfo | None = None) -> str:
    """Compact single-line form for window titles and status bars."""
    if info is None:
        info = version_info()
    built = info.built_at[:19].replace("T", " ") if info.built_at != UNKNOWN else "未构建"
    return f"v{info.version} · commit {info.commit} · 构建 {built}"
