"""Accessory affix (词条) catalog built from the 仁王3词条装备库v2.21.xlsx.

The catalog is a JSON file (``data/accessory_affixes.json``) generated by
``tools/build_affix_db.py`` from the workbook's 饰品词条 sheet (309 rows).
Each entry records:

* ``effect_id`` — u32 little-endian value from bytes 0..3 of the 词条代码.
* ``value`` — u32 value from bytes 4..7 (the nominal display value).
* ``flags`` — metadata bits: 0x40 = 同名固定, 0x04 = 星号.
* ``name`` — display name including the (同名固定)/(星) prefix.
* ``category`` — the 类别 column (造成伤害/精力减少/...).

``AffixDb`` provides id->name lookup and validation used by the editor to fail
closed on anything outside the accessory table.  A catalog containing duplicate
effect ids is rejected outright: the editor resolves edits by id, so an
ambiguous id could silently apply the wrong value.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from .paths import default_catalog_path, default_grace_path

__all__ = [
    "DEFAULT_CATALOG",
    "DEFAULT_GRACE_CATALOG",
    "FLAG_FIXED",
    "FLAG_STAR",
    "AffixDb",
    "AffixEntry",
    "AffixError",
    "GraceDb",
    "load_catalog",
    "load_grace_catalog",
    "save_catalog",
    "save_grace_catalog",
]

DEFAULT_CATALOG = default_catalog_path()
CATALOG_SCHEMA = "nioh3-accessory-affixes/v1"

#: 恩宠 / 套装组合 names.  These ids are **not** legal accessory affixes (armour
#: carries 套装 codes), so they live in their own table used for display only:
#: every real accessory ends with one of them (e.g. 稻荷神的恩宠 on a 龙笛), and
#: without the table the editor could only call that slot an unknown affix.
DEFAULT_GRACE_CATALOG = default_grace_path()
GRACE_CATALOG_SCHEMA = "nioh3-grace-affixes/v1"

# Metadata flag bits decoded from the 词条代码 byte layout:
# byte 9 bit6 = 固定 (同名固定 variants carry 0x43/0x45/0x46), byte 10 bit2 = 星.
FLAG_FIXED = 0x40
FLAG_STAR = 0x04

EMPTY_EFFECT_ID = 0xFFFFFFFF
_UINT32_MAX = 0xFFFFFFFF


class AffixError(ValueError):
    """Raised when an affix is not in the legal accessory catalog."""


@dataclass(frozen=True, slots=True)
class AffixEntry:
    effect_id: int
    value: int
    flags: int
    name: str
    category: str

    @property
    def is_fixed(self) -> bool:
        return bool(self.flags & FLAG_FIXED)

    @property
    def is_star(self) -> bool:
        return bool(self.flags & FLAG_STAR)

    @property
    def label(self) -> str:
        """Stable combo-box label: ``0x0b32 (同名固定)守护灵技的伤害 +20.0%``."""
        return f"{self.effect_id:#06x} {self.name}"


class AffixDb:
    """Immutable catalog of legal accessory affixes with id lookups."""

    __slots__ = ("_entries", "_by_id", "catalog_path")

    def __init__(
        self,
        entries: list[AffixEntry] | None = None,
        catalog_path: Path = DEFAULT_CATALOG,
    ) -> None:
        self.catalog_path = catalog_path
        self._entries = tuple(entries) if entries is not None else tuple(load_catalog(catalog_path))
        by_id: dict[int, AffixEntry] = {}
        for entry in self._entries:
            if entry.effect_id in by_id:
                raise AffixError(
                    f"词条库存在重复的词条 ID {entry.effect_id:#x}；"
                    "请重新生成词条库（tools/build_affix_db.py）"
                )
            by_id[entry.effect_id] = entry
        self._by_id = by_id

    @classmethod
    def from_file(cls, catalog_path: Path = DEFAULT_CATALOG) -> "AffixDb":
        return cls(catalog_path=catalog_path)

    def __len__(self) -> int:
        return len(self._entries)

    def __contains__(self, effect_id: object) -> bool:
        return effect_id in self._by_id

    def lookup(self, effect_id: int) -> AffixEntry | None:
        return self._by_id.get(effect_id)

    def is_legal(self, effect_id: int) -> bool:
        return effect_id in self._by_id

    def require(self, effect_id: int) -> AffixEntry:
        entry = self.lookup(effect_id)
        if entry is None:
            raise AffixError(f"词条 {effect_id:#010x} 不在合法的饰品词条表中")
        return entry

    def describe(self, effect_id: int) -> str:
        entry = self.lookup(effect_id)
        if entry is None:
            return f"未知词条 {effect_id:#010x}"
        return entry.name

    def all(self) -> tuple[AffixEntry, ...]:
        return self._entries

    def by_category(self, category: str | None = None) -> tuple[AffixEntry, ...]:
        if category is None:
            return self._entries
        return tuple(entry for entry in self._entries if entry.category == category)

    def categories(self) -> tuple[str, ...]:
        seen: list[str] = []
        for entry in self._entries:
            if entry.category not in seen:
                seen.append(entry.category)
        return tuple(seen)

    def labels(self) -> tuple[str, ...]:
        """Combo-box labels, prefixed with the empty-slot choice."""
        return ("(空)",) + tuple(entry.label for entry in self._entries)


def _require_uint32(payload: dict[str, object], key: str, where: str) -> int:
    value = payload.get(key)
    if not isinstance(value, int) or isinstance(value, bool):
        raise AffixError(f"{where}: 字段 {key} 必须是整数，实际 {value!r}")
    if not 0 <= value <= _UINT32_MAX:
        raise AffixError(f"{where}: 字段 {key} 超出 uint32 范围：{value}")
    return value


def load_catalog(path: Path = DEFAULT_CATALOG) -> list[AffixEntry]:
    """Load entries from the generated JSON catalog, validating every field."""
    payload = _load_payload(path, "词条库")
    return _entries_from_payload(payload, path)


def load_grace_catalog(path: Path = DEFAULT_GRACE_CATALOG) -> list[AffixEntry]:
    """Load the 恩宠/套装 name table (display only, never used for legality)."""
    payload = _load_payload(path, "恩宠/套装名表")
    return _entries_from_payload(payload, path)


def _load_payload(path: Path, what: str) -> dict:
    if not path.is_file():
        raise AffixError(f"缺少{what}文件 {path}；请先运行 tools/build_affix_db.py 生成")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise AffixError(f"{what}文件无法解析：{path}（{error}）") from error
    if not isinstance(payload, dict):
        raise AffixError(f"{what}文件格式错误：{path} 顶层必须是对象")
    raw_entries = payload.get("affixes")
    if not isinstance(raw_entries, list) or not raw_entries:
        raise AffixError(f"{what}文件没有 affixes 列表：{path}")

    declared = payload.get("count")
    if isinstance(declared, int) and declared != len(raw_entries):
        raise AffixError(
            f"{what}文件自述 {declared} 条但实际包含 {len(raw_entries)} 条：{path}"
        )
    return payload


def _entries_from_payload(payload: dict, path: Path) -> list[AffixEntry]:
    entries: list[AffixEntry] = []
    for index, item in enumerate(payload["affixes"]):
        where = f"第 {index + 1} 条"
        if not isinstance(item, dict):
            raise AffixError(f"{where}: 词条条目必须是对象")
        name = item.get("name")
        category = item.get("category")
        if not isinstance(name, str) or not name.strip():
            raise AffixError(f"{where}: 缺少词条名称")
        if not isinstance(category, str):
            raise AffixError(f"{where}: 缺少词条类别")
        entries.append(
            AffixEntry(
                effect_id=_require_uint32(item, "effect_id", where),
                value=_require_uint32(item, "value", where),
                flags=_require_uint32(item, "flags", where),
                name=name.strip(),
                category=category.strip(),
            )
        )
    return entries


def save_catalog(
    entries: list[AffixEntry],
    path: Path = DEFAULT_CATALOG,
    *,
    source: str = "",
    conflicts: list[str] | None = None,
    schema: str = CATALOG_SCHEMA,
    default_source: str = "仁王3词条装备库v2.21.xlsx / 饰品词条",
) -> None:
    """Write entries as the JSON catalog (used by the build tool)."""
    seen: set[int] = set()
    for entry in entries:
        if entry.effect_id in seen:
            raise AffixError(f"拒绝写出含重复词条 ID 的词条库：{entry.effect_id:#x}")
        seen.add(entry.effect_id)
    payload = {
        "schema": schema,
        "count": len(entries),
        "source": source or default_source,
        "conflicts": conflicts or [],
        "affixes": [
            {
                "effect_id": entry.effect_id,
                "value": entry.value,
                "flags": entry.flags,
                "name": entry.name,
                "category": entry.category,
            }
            for entry in entries
        ],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n": the catalog is a committed text file, so its bytes must not
    # depend on the platform that regenerated it.
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
                    encoding="utf-8", newline="\n")


def save_grace_catalog(
    entries: list[AffixEntry],
    path: Path = DEFAULT_GRACE_CATALOG,
    *,
    source: str = "",
) -> None:
    """Write the 恩宠/套装 name table (same JSON shape, its own schema)."""
    save_catalog(
        entries, path, source=source, schema=GRACE_CATALOG_SCHEMA,
        default_source="仁王3词条装备库v2.21.xlsx / 词条总目录（恩宠·套装）",
    )


class GraceDb:
    """Name lookup for the 恩宠/套装 ids that end an accessory's affix list.

    Display only: :class:`AffixDb` still decides what may be *written*.  Missing
    or unreadable table degrades to "no names" instead of failing the app, so a
    user who never regenerated the data still gets the earlier wording.
    """

    __slots__ = ("_entries", "_by_id", "catalog_path", "error")

    def __init__(
        self,
        entries: list[AffixEntry] | None = None,
        catalog_path: Path = DEFAULT_GRACE_CATALOG,
        *,
        error: str = "",
    ) -> None:
        self.catalog_path = catalog_path
        self.error = error
        self._entries = tuple(entries) if entries is not None else ()
        by_id: dict[int, AffixEntry] = {}
        for entry in self._entries:
            by_id.setdefault(entry.effect_id, entry)
        self._by_id = by_id

    @classmethod
    def from_file(cls, catalog_path: Path = DEFAULT_GRACE_CATALOG) -> "GraceDb":
        return cls(load_grace_catalog(catalog_path), catalog_path)

    @classmethod
    def best_effort(cls, catalog_path: Path | None = None) -> "GraceDb":
        """Load the table, or return an empty one carrying the reason."""
        path = DEFAULT_GRACE_CATALOG if catalog_path is None else catalog_path
        try:
            return cls.from_file(path)
        except AffixError as error:
            return cls(catalog_path=path, error=str(error))

    @property
    def is_loaded(self) -> bool:
        return bool(self._entries)

    def __len__(self) -> int:
        return len(self._entries)

    def __contains__(self, effect_id: object) -> bool:
        return effect_id in self._by_id

    def lookup(self, effect_id: int) -> AffixEntry | None:
        return self._by_id.get(effect_id)

    def describe(self, effect_id: int) -> str | None:
        """``稻荷神的恩宠（恩宠）`` — ``None`` when the id is not in the table."""
        entry = self.lookup(effect_id)
        if entry is None:
            return None
        if entry.category:
            return f"{entry.name}（{entry.category}）"
        return entry.name

    def all(self) -> tuple[AffixEntry, ...]:
        return self._entries
