"""Accessory affix (词条) catalog built from the 仁王3词条装备库v2.21.xlsx.

The catalog is a JSON file (``data/accessory_affixes.json``) generated by
``tools/build_affix_db.py`` from the workbook's 饰品词条 sheet (309 rows).
Each entry records:

* ``effect_id`` — u32 little-endian value from bytes 0..3 of the 词条代码.
* ``value`` — u32 value from bytes 4..7 (the nominal display value).
* ``flags`` — metadata bits: 0x40 = 同名固定, 0x04 = 星号.
* ``name`` — display name including the (同名固定)/(星) prefix.
* ``category`` — the 类别 column (造成伤害/精力减少/...).

``AffixDb`` provides id->name lookup and validation used by the editor to fail
closed on anything outside the accessory table.  A catalog containing duplicate
effect ids is rejected outright: the editor resolves edits by id, so an
ambiguous id could silently apply the wrong value.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from .paths import (
    default_catalog_path,
    default_grace_path,
    default_items_path,
    default_soul_catalog_path,
    default_soul_items_path,
)

__all__ = [
    "DEFAULT_CATALOG",
    "DEFAULT_GRACE_CATALOG",
    "DEFAULT_ITEM_CATALOG",
    "FLAG_FIXED",
    "FLAG_STAR",
    "GRACE_KINDS",
    "ITEM_CATALOG_SCHEMA",
    "AffixDb",
    "AffixEntry",
    "AffixError",
    "GraceDb",
    "ItemDb",
    "ItemEntry",
    "load_catalog",
    "load_grace_catalog",
    "load_item_catalog",
    "save_catalog",
    "save_grace_catalog",
    "save_item_catalog",
    "save_soul_catalog",
    "save_soul_item_catalog",
    "load_soul_catalog",
    "load_soul_item_catalog",
    "DEFAULT_SOUL_CATALOG",
    "DEFAULT_SOUL_ITEM_CATALOG",
    "SOUL_CATALOG_SCHEMA",
    "SOUL_ITEM_CATALOG_SCHEMA",
]

DEFAULT_CATALOG = default_catalog_path()
CATALOG_SCHEMA = "nioh3-accessory-affixes/v1"

#: 恩宠 / 套装组合 names.  These ids are **not** legal accessory affixes (armour
#: carries 套装 codes), so they live in their own table used for display only:
#: every real accessory ends with one of them (e.g. 稻荷神的恩宠 on a 龙笛), and
#: without the table the editor could only call that slot an unknown affix.
DEFAULT_GRACE_CATALOG = default_grace_path()
GRACE_CATALOG_SCHEMA = "nioh3-grace-affixes/v1"

#: 归属 values that describe a *changeable* 恩宠 (a name ending in 的恩宠).  The
#: 套装 kinds are listed in the same table but must never be written: the game
#: keeps item-specific 套装 effects (e.g. 怨恨盖世) in a different family byte.
GRACE_KINDS = ("恩宠", "上位恩宠")

#: The 饰品 rows of 物品总目录 — what an accessory *is* (its 种类), keyed by the
#: per-item id the record header carries in v2.21.  Display only, like the grace
#: table: the ids live in a different space from 词条 ids, and nothing here may
#: ever authorise a write.  Measured on the reference save: 212 of 213
#: accessories resolve to one of these 88 ids.
DEFAULT_ITEM_CATALOG = default_items_path()
ITEM_CATALOG_SCHEMA = "nioh3-accessory-items/v1"

#: 魂核 (soul cores) have their own affix pool: 绘卷-魂核词条, 种类 = 魂核 → 287 ids in
#: v2.21, of which exactly one id also appears in the 饰品词条 table.  A 魂核 has no
#: 恩宠/套装 affix, so its edits are gated by this table (and its own item table).
DEFAULT_SOUL_CATALOG = default_soul_catalog_path()
SOUL_CATALOG_SCHEMA = "nioh3-soul-affixes/v1"

#: 魂核 rows of 物品总目录 (大类 = 魂核, 83 ids in v2.21) — what a 魂核 *is*.
DEFAULT_SOUL_ITEM_CATALOG = default_soul_items_path()
SOUL_ITEM_CATALOG_SCHEMA = "nioh3-soul-items/v1"

# Metadata flag bits decoded from the 词条代码 byte layout:
# byte 9 bit6 = 固定 (同名固定 variants carry 0x43/0x45/0x46), byte 10 bit2 = 星.
FLAG_FIXED = 0x40
FLAG_STAR = 0x04

EMPTY_EFFECT_ID = 0xFFFFFFFF
_UINT32_MAX = 0xFFFFFFFF


class AffixError(ValueError):
    """Raised when an affix is not in the legal accessory catalog."""


@dataclass(frozen=True, slots=True)
class AffixEntry:
    effect_id: int
    value: int
    flags: int
    name: str
    category: str
    #: Legal value span of this affix, from the workbook's own value table
    #: (全词条数值 取值集合 for 饰品, 数值区间/数值集合 for 魂核).  ``None`` means the
    #: workbook gave no span, and then the editor refuses to write any value other
    #: than the catalog's own — guessing a range would be exactly the kind of
    #: unverified write this tool must not do.  Measured on the reference save's
    #: save: all 807 catalogued accessory slots hold a value inside their span.
    value_min: int | None = None
    value_max: int | None = None
    #: The workbook's own 数值集合 when it is **not** every integer of the span (e.g.
    #: 绿色星号词条 0x248c allows 470,472,475,…,520).  ``None`` means "the whole span",
    #: which is what every other catalog row is (measured).
    values: tuple[int, ...] | None = None

    @property
    def is_fixed(self) -> bool:
        return bool(self.flags & FLAG_FIXED)

    @property
    def is_star(self) -> bool:
        return bool(self.flags & FLAG_STAR)

    @property
    def has_value_range(self) -> bool:
        return self.value_min is not None and self.value_max is not None

    def allows_value(self, value: int) -> bool:
        """Whether ``value`` is one the workbook lists for this affix.

        An explicit 数值集合 wins over the span: the green sheet has rows whose legal
        values step by 2.5 (470, 472, 475, …), and writing 471 or 473 would be a
        value the game never rolls.
        """
        if self.values:
            return value in self.values
        if not self.has_value_range:
            return False
        return bool(self.value_min <= value <= self.value_max)  # type: ignore[operator]

    def describe_value_range(self) -> str:
        if self.values:
            listed = "、".join(str(value) for value in self.values)
            if len(self.values) <= 8:
                return f"取值 {listed}"
            return (f"{self.value_min}..{self.value_max} 共 {len(self.values)} 个取值"
                    f"（{self.values[0]}、{self.values[1]}…{self.values[-1]}）")
        if not self.has_value_range:
            return "数值区间未知（原始表未给出）"
        if self.value_min == self.value_max:
            return f"固定值 {self.value_min}"
        return f"{self.value_min}..{self.value_max}"

    @property
    def label(self) -> str:
        """Stable combo-box label: ``0x0b32 (同名固定)守护灵技的伤害 +20.0%``."""
        return f"{self.effect_id:#06x} {self.name}"


class AffixDb:
    """Immutable catalog of legal accessory affixes with id lookups."""

    __slots__ = ("_entries", "_by_id", "catalog_path")

    def __init__(
        self,
        entries: list[AffixEntry] | None = None,
        catalog_path: Path = DEFAULT_CATALOG,
    ) -> None:
        self.catalog_path = catalog_path
        self._entries = tuple(entries) if entries is not None else tuple(load_catalog(catalog_path))
        by_id: dict[int, AffixEntry] = {}
        for entry in self._entries:
            if entry.effect_id in by_id:
                raise AffixError(
                    f"词条库存在重复的词条 ID {entry.effect_id:#x}；"
                    "请重新生成词条库（tools/build_affix_db.py）"
                )
            by_id[entry.effect_id] = entry
        self._by_id = by_id

    @classmethod
    def from_file(cls, catalog_path: Path = DEFAULT_CATALOG) -> "AffixDb":
        return cls(catalog_path=catalog_path)

    def __len__(self) -> int:
        return len(self._entries)

    def __contains__(self, effect_id: object) -> bool:
        return effect_id in self._by_id

    def lookup(self, effect_id: int) -> AffixEntry | None:
        return self._by_id.get(effect_id)

    def is_legal(self, effect_id: int) -> bool:
        return effect_id in self._by_id

    def require(self, effect_id: int) -> AffixEntry:
        entry = self.lookup(effect_id)
        if entry is None:
            raise AffixError(f"词条 {effect_id:#010x} 不在合法的饰品词条表中")
        return entry

    def describe(self, effect_id: int) -> str:
        entry = self.lookup(effect_id)
        if entry is None:
            return f"未知词条 {effect_id:#010x}"
        return entry.name

    def all(self) -> tuple[AffixEntry, ...]:
        return self._entries

    def by_category(self, category: str | None = None) -> tuple[AffixEntry, ...]:
        if category is None:
            return self._entries
        return tuple(entry for entry in self._entries if entry.category == category)

    def categories(self) -> tuple[str, ...]:
        seen: list[str] = []
        for entry in self._entries:
            if entry.category not in seen:
                seen.append(entry.category)
        return tuple(seen)

    def labels(self) -> tuple[str, ...]:
        """Combo-box labels, prefixed with the empty-slot choice."""
        return ("(空)",) + tuple(entry.label for entry in self._entries)

    @staticmethod
    def _token_matches(entry: AffixEntry, token: str) -> bool:
        """One keyword against one entry: name, category, or id text."""
        token = token.lower()
        compact = token.replace(" ", "")
        return bool(
            token in entry.name.lower()
            or token in entry.category.lower()
            or compact in entry.name.lower().replace(" ", "")
            or compact in f"{entry.effect_id:#x}".lower()
        )

    def search(self, keyword: str, *, limit: int = 0) -> tuple[AffixEntry, ...]:
        """Every entry matching **all** keywords, which are separated by spaces.

        ``星 恢复`` therefore means "the name must contain 星 *and* 恢复", which is
        how a list of 308 catalogued affixes stays usable.  A single keyword behaves
        exactly as before.  Typing a keyword must never silently pick one affix: the
        caller shows the whole match list (empty, one, or many) and the user chooses
        from it.  A blank keyword matches nothing, so an empty search box can never
        be mistaken for "everything".
        """
        tokens = [token for token in keyword.replace("\u3000", " ").split() if token]
        if not tokens:
            return ()
        matches = [entry for entry in self._entries
                   if all(self._token_matches(entry, token) for token in tokens)]
        if limit > 0:
            return tuple(matches[:limit])
        return tuple(matches)


def _require_uint32(payload: dict[str, object], key: str, where: str) -> int:
    value = payload.get(key)
    if not isinstance(value, int) or isinstance(value, bool):
        raise AffixError(f"{where}: 字段 {key} 必须是整数，实际 {value!r}")
    if not 0 <= value <= _UINT32_MAX:
        raise AffixError(f"{where}: 字段 {key} 超出 uint32 范围：{value}")
    return value


def load_catalog(path: Path = DEFAULT_CATALOG) -> list[AffixEntry]:
    """Load entries from the generated JSON catalog, validating every field."""
    payload = _load_payload(path, "词条库")
    return _entries_from_payload(payload, path)


def load_grace_catalog(path: Path = DEFAULT_GRACE_CATALOG) -> list[AffixEntry]:
    """Load the 恩宠/套装 name table (display only, never used for legality)."""
    payload = _load_payload(path, "恩宠/套装名表")
    return _entries_from_payload(payload, path)


def load_soul_catalog(path: Path = DEFAULT_SOUL_CATALOG) -> list[AffixEntry]:
    """Load the legal 魂核 affix table (绘卷-魂核词条, 种类=魂核)."""
    payload = _load_payload(path, "魂核词条库")
    return _entries_from_payload(payload, path)


def load_soul_item_catalog(path: Path = DEFAULT_SOUL_ITEM_CATALOG) -> list[ItemEntry]:
    """Load the 魂核 item table (物品总目录 大类=魂核; display only)."""
    payload = _load_payload(path, "魂核物品种类表", list_key="items")
    raw_items = payload["items"]
    entries: list[ItemEntry] = []
    for index, raw in enumerate(raw_items):
        where = f"{path} 第 {index + 1} 条"
        if not isinstance(raw, dict):
            raise AffixError(f"{where} 必须是对象")
        item_id = _require_uint32(raw, "item_id", where)
        name = raw.get("name")
        category = raw.get("category", "")
        if not isinstance(name, str) or not name.strip():
            raise AffixError(f"{where} 缺少 name")
        if not isinstance(category, str):
            raise AffixError(f"{where} 的 category 必须是字符串")
        entries.append(ItemEntry(item_id=item_id, name=name.strip(),
                                 category=category.strip()))
    return entries


def save_soul_catalog(
    entries: list[AffixEntry],
    path: Path = DEFAULT_SOUL_CATALOG,
    *,
    conflicts: list[str] | None = None,
    source: str = "",
) -> None:
    """Write the 魂核 affix table (its own schema, same JSON shape)."""
    save_catalog(
        entries, path, source=source, schema=SOUL_CATALOG_SCHEMA,
        conflicts=conflicts,
        default_source="仁王3词条装备库v2.21.xlsx / 绘卷-魂核词条（魂核）",
    )


def save_soul_item_catalog(
    entries: list[ItemEntry],
    path: Path = DEFAULT_SOUL_ITEM_CATALOG,
    *,
    conflicts: list[str] | None = None,
    source: str = "",
) -> None:
    """Write the 魂核 item table (物品总目录 大类=魂核; display only)."""
    save_item_catalog(
        entries, path, source=source, conflicts=conflicts,
        schema=SOUL_ITEM_CATALOG_SCHEMA,
        default_source="仁王3词条装备库v2.21.xlsx / 物品总目录（魂核）",
    )


def _load_payload(path: Path, what: str, *,
                  list_key: str = "affixes") -> dict:
    if not path.is_file():
        raise AffixError(f"缺少{what}文件 {path}；请先运行 tools/build_affix_db.py 生成")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise AffixError(f"{what}文件无法解析：{path}（{error}）") from error
    if not isinstance(payload, dict):
        raise AffixError(f"{what}文件格式错误：{path} 顶层必须是对象")
    raw_entries = payload.get(list_key)
    if not isinstance(raw_entries, list) or not raw_entries:
        raise AffixError(f"{what}文件没有 {list_key} 列表：{path}")

    declared = payload.get("count")
    if isinstance(declared, int) and declared != len(raw_entries):
        raise AffixError(
            f"{what}文件自述 {declared} 条但实际包含 {len(raw_entries)} 条：{path}"
        )
    return payload


def _entries_from_payload(payload: dict, path: Path) -> list[AffixEntry]:
    entries: list[AffixEntry] = []
    for index, item in enumerate(payload["affixes"]):
        where = f"第 {index + 1} 条"
        if not isinstance(item, dict):
            raise AffixError(f"{where}: 词条条目必须是对象")
        name = item.get("name")
        category = item.get("category")
        if not isinstance(name, str) or not name.strip():
            raise AffixError(f"{where}: 缺少词条名称")
        if not isinstance(category, str):
            raise AffixError(f"{where}: 缺少词条类别")
        entries.append(
            AffixEntry(
                effect_id=_require_uint32(item, "effect_id", where),
                value=_require_uint32(item, "value", where),
                flags=_require_uint32(item, "flags", where),
                name=name.strip(),
                category=category.strip(),
                values=_optional_value_set(item, where),
        value_min=_optional_uint32(item, "value_min", where),
                value_max=_optional_uint32(item, "value_max", where),
            )
        )
    return entries


def _optional_value_set(item: dict, where: str) -> tuple[int, ...] | None:
    """Read an explicit 数值集合, rejecting anything that is not ascending ints."""
    raw = item.get("values")
    if raw is None:
        return None
    if not isinstance(raw, list) or not raw:
        raise AffixError(f"{where}: values 必须是非空数组")
    numbers = []
    for value in raw:
        number = _require_uint32({"v": value}, "v", where)
        numbers.append(number)
    if numbers != sorted(set(numbers)):
        raise AffixError(f"{where}: values 必须去重且升序")
    return tuple(numbers)


def _optional_uint32(item: dict, key: str, where: str) -> int | None:
    """Read an optional unsigned int; a present-but-invalid value is an error."""
    if key not in item or item[key] is None:
        return None
    return _require_uint32(item, key, where)


def save_catalog(
    entries: list[AffixEntry],
    path: Path = DEFAULT_CATALOG,
    *,
    source: str = "",
    conflicts: list[str] | None = None,
    schema: str = CATALOG_SCHEMA,
    default_source: str = "仁王3词条装备库v2.21.xlsx / 饰品词条",
) -> None:
    """Write entries as the JSON catalog (used by the build tool)."""
    seen: set[int] = set()
    for entry in entries:
        if entry.effect_id in seen:
            raise AffixError(f"拒绝写出含重复词条 ID 的词条库：{entry.effect_id:#x}")
        seen.add(entry.effect_id)
    payload = {
        "schema": schema,
        "count": len(entries),
        "source": source or default_source,
        "conflicts": conflicts or [],
        "affixes": [
            {
                "effect_id": entry.effect_id,
                "value": entry.value,
                "flags": entry.flags,
                "name": entry.name,
                "category": entry.category,
                **({"values": list(entry.values)} if entry.values else {}),
            **({"value_min": entry.value_min, "value_max": entry.value_max}
                   if entry.has_value_range else {}),
            }
            for entry in entries
        ],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n": the catalog is a committed text file, so its bytes must not
    # depend on the platform that regenerated it.
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
                    encoding="utf-8", newline="\n")


def save_grace_catalog(
    entries: list[AffixEntry],
    path: Path = DEFAULT_GRACE_CATALOG,
    *,
    source: str = "",
) -> None:
    """Write the 恩宠/套装 name table (same JSON shape, its own schema)."""
    save_catalog(
        entries, path, source=source, schema=GRACE_CATALOG_SCHEMA,
        default_source="仁王3词条装备库v2.21.xlsx / 词条总目录（恩宠·套装）",
    )


@dataclass(frozen=True, slots=True)
class ItemEntry:
    """One 饰品 row of 物品总目录: what an accessory *is*, not what it carries."""

    item_id: int
    name: str
    category: str
    #: Where this row came from, when it is not simply "the workbook says so" —
    #: e.g. an id the workbook cannot express (0x5c5f 八咫镜[武士], see
    #: ``tools/build_affix_db.py``).  Empty for plain 物品总目录 rows.
    source: str = ""

    @property
    def label(self) -> str:
        """``0x4987 八尺琼勾玉[武士]``."""
        return f"{self.item_id:#06x} {self.name}"


class ItemDb:
    """Name lookup for the item id an accessory record carries (display only).

    A v2.21 record's header field at ``+0x00`` (mirrored at ``+0x02``) holds the
    *item* id, not the captured category type: measured on the reference save's
    save, 212 of 213 accessories resolve to a 饰品 row of 物品总目录.  This table
    answers "which accessory is this?", and — like :class:`GraceDb` — never
    decides what may be written.  A missing table degrades to "no names".
    """

    __slots__ = ("_entries", "_by_id", "catalog_path", "error")

    def __init__(
        self,
        entries: list[ItemEntry] | None = None,
        catalog_path: Path = DEFAULT_ITEM_CATALOG,
        *,
        error: str = "",
    ) -> None:
        self.catalog_path = catalog_path
        self.error = error
        self._entries = tuple(entries) if entries is not None else ()
        by_id: dict[int, ItemEntry] = {}
        for entry in self._entries:
            by_id.setdefault(entry.item_id, entry)
        self._by_id = by_id

    @classmethod
    def from_file(cls, catalog_path: Path = DEFAULT_ITEM_CATALOG) -> "ItemDb":
        return cls(load_item_catalog(catalog_path), catalog_path)

    @classmethod
    def best_effort(cls, catalog_path: Path | None = None) -> "ItemDb":
        """Load the table, or return an empty one carrying the reason."""
        path = DEFAULT_ITEM_CATALOG if catalog_path is None else catalog_path
        try:
            return cls.from_file(path)
        except AffixError as error:
            return cls(catalog_path=path, error=str(error))

    @property
    def is_loaded(self) -> bool:
        return bool(self._entries)

    def __len__(self) -> int:
        return len(self._entries)

    def __contains__(self, item_id: object) -> bool:
        return item_id in self._by_id

    def lookup(self, item_id: int) -> ItemEntry | None:
        return self._by_id.get(item_id)

    def describe(self, item_id: int) -> str | None:
        """``八尺琼勾玉[武士]`` — ``None`` when the id is not in the table."""
        entry = self.lookup(item_id)
        return None if entry is None else entry.name

    def category_of(self, item_id: int) -> str | None:
        """中类 of an item (``武士饰品``/``忍者饰品``), or ``None`` if unknown.

        Evidence for the 改种类 rule: only items of the same 中类 may be swapped,
        and an id that is not in the table (or whose row has no 中类) cannot be
        shown to be in the same 中类, so it can never take part in a swap.
        """
        entry = self.lookup(item_id)
        if entry is None or not entry.category:
            return None
        return entry.category

    def all(self) -> tuple[ItemEntry, ...]:
        return self._entries

    def categories(self) -> tuple[str, ...]:
        seen: list[str] = []
        for entry in self._entries:
            if entry.category not in seen:
                seen.append(entry.category)
        return tuple(seen)

    def labels(self) -> tuple[str, ...]:
        """``0x4987 八尺琼勾玉[武士]`` for every row, for comboboxes."""
        return tuple(entry.label for entry in self._entries)

    def search(self, keyword: str, *, limit: int = 0) -> tuple[AffixEntry, ...]:
        """Every entry whose name, category or id text contains ``keyword``.

        Typing a keyword must never silently pick an affix: the caller shows the
        whole match list (which may be empty, one, or many) and the user chooses.
        A blank keyword matches nothing, so an empty search box cannot be mistaken
        for "everything".
        """
        text = keyword.strip().lower()
        if not text:
            return ()
        compact = text.replace(" ", "")
        matches = [
            entry for entry in self._entries
            if text in entry.name.lower() or text in entry.category.lower()
            or compact in entry.name.lower().replace(" ", "")
            or compact in f"{entry.effect_id:#06x}".lower()
            or compact in f"{entry.effect_id:#x}".lower()
        ]
        if limit > 0:
            return tuple(matches[:limit])
        return tuple(matches)


    def search(self, keyword: str, *, limit: int = 0) -> tuple[ItemEntry, ...]:
        """Item rows whose name or category contains ``keyword`` (filtering)."""
        text = keyword.strip().lower()
        if not text:
            return ()
        matches = [entry for entry in self._entries
                   if text in entry.name.lower() or text in entry.category.lower()]
        return tuple(matches[:limit]) if limit > 0 else tuple(matches)

    def items_in_category(self, category: str | None) -> tuple[ItemEntry, ...]:
        """Every row of one 中类 (``None``/blank means "no filter")."""
        if not category:
            return self._entries
        return tuple(entry for entry in self._entries
                     if entry.category == category)


def load_item_catalog(path: Path = DEFAULT_ITEM_CATALOG) -> list[ItemEntry]:
    """Load the 饰品 item table (display only, never used for legality)."""
    payload = _load_payload(path, "物品种类表", list_key="items")
    entries: list[ItemEntry] = []
    for index, item in enumerate(payload["items"]):
        where = f"第 {index + 1} 条"
        if not isinstance(item, dict):
            raise AffixError(f"{where}: 物品条目必须是对象")
        name = item.get("name")
        category = item.get("category")
        if not isinstance(name, str) or not name.strip():
            raise AffixError(f"{where}: 缺少物品名称")
        if not isinstance(category, str):
            raise AffixError(f"{where}: 缺少物品分类")
        source = item.get("source", "")
        if not isinstance(source, str):
            raise AffixError(f"{where}: source 必须是字符串")
        entries.append(
            ItemEntry(
                item_id=_require_uint32(item, "item_id", where),
                name=name.strip(),
                category=category.strip(),
                source=source.strip(),
            )
        )
    return entries


def save_item_catalog(
    entries: list[ItemEntry],
    path: Path = DEFAULT_ITEM_CATALOG,
    *,
    source: str = "",
    conflicts: list[str] | None = None,
    schema: str = ITEM_CATALOG_SCHEMA,
    default_source: str = "仁王3词条装备库v2.21.xlsx / 物品总目录（饰品）",
) -> None:
    """Write an item table (same envelope, its own ``items`` list)."""
    seen: set[int] = set()
    for entry in entries:
        if entry.item_id in seen:
            raise AffixError(f"拒绝写出含重复物品 ID 的表：{entry.item_id:#x}")
        seen.add(entry.item_id)
    payload = {
        "schema": schema,
        "count": len(entries),
        "source": source or default_source,
        "conflicts": conflicts or [],
        "items": [
            {"item_id": entry.item_id, "name": entry.name,
             "category": entry.category,
             **({"source": entry.source} if entry.source else {})}
            for entry in entries
        ],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
                    encoding="utf-8", newline="\n")


class GraceDb:
    """Name lookup for the 恩宠/套装 ids that end an accessory's affix list.

    Display only: :class:`AffixDb` still decides what may be *written*.  Missing
    or unreadable table degrades to "no names" instead of failing the app, so a
    user who never regenerated the data still gets the earlier wording.
    """

    __slots__ = ("_entries", "_by_id", "catalog_path", "error")

    def __init__(
        self,
        entries: list[AffixEntry] | None = None,
        catalog_path: Path = DEFAULT_GRACE_CATALOG,
        *,
        error: str = "",
    ) -> None:
        self.catalog_path = catalog_path
        self.error = error
        self._entries = tuple(entries) if entries is not None else ()
        by_id: dict[int, AffixEntry] = {}
        for entry in self._entries:
            by_id.setdefault(entry.effect_id, entry)
        self._by_id = by_id

    @classmethod
    def from_file(cls, catalog_path: Path = DEFAULT_GRACE_CATALOG) -> "GraceDb":
        return cls(load_grace_catalog(catalog_path), catalog_path)

    @classmethod
    def best_effort(cls, catalog_path: Path | None = None) -> "GraceDb":
        """Load the table, or return an empty one carrying the reason."""
        path = DEFAULT_GRACE_CATALOG if catalog_path is None else catalog_path
        try:
            return cls.from_file(path)
        except AffixError as error:
            return cls(catalog_path=path, error=str(error))

    @property
    def is_loaded(self) -> bool:
        return bool(self._entries)

    def __len__(self) -> int:
        return len(self._entries)

    def __contains__(self, effect_id: object) -> bool:
        return effect_id in self._by_id

    def lookup(self, effect_id: int) -> AffixEntry | None:
        return self._by_id.get(effect_id)

    def describe(self, effect_id: int) -> str | None:
        """``稻荷神的恩宠（恩宠）`` — ``None`` when the id is not in the table."""
        entry = self.lookup(effect_id)
        if entry is None:
            return None
        if entry.category:
            return f"{entry.name}（{entry.category}）"
        return entry.name

    def of_kind(self, *kinds: str) -> tuple[AffixEntry, ...]:
        """Entries whose 归属 is one of ``kinds`` (e.g. 恩宠 / 上位恩宠)."""
        return tuple(entry for entry in self._entries if entry.category in kinds)

    def grace_entries(self) -> tuple[AffixEntry, ...]:
        """Only the changeable 恩宠/上位恩宠 entries (never the 套装 ones)."""
        return self.of_kind(*GRACE_KINDS)

    def labels(self) -> tuple[str, ...]:
        """Combo-box labels for the changeable 恩宠: ``0x4fa3 稻荷神的恩宠（恩宠）``."""
        return tuple(f"{entry.effect_id:#06x} {entry.name}（{entry.category}）"
                     for entry in self.grace_entries())

    def all(self) -> tuple[AffixEntry, ...]:
        return self._entries
