"""Tkinter GUI for Nioh3AccessoryEditor (zero third-party dependencies).

Workflow:
1. 刷新 -> discover saves, decrypt the selected one, scan accessory records.
2. Pick an accessory record in the tree, edit its 7 affix slots with searchable
   legal-affix dropdowns, click 应用修改, then 写入存档.
3. Every write: quiescence re-check, checksum recompute, plaintext backup,
   staged verification, atomic durable replacement, post-write verification.

The window shows the required disclaimer permanently.
"""

from __future__ import annotations

import os
import queue
import threading
import time
import tkinter as tk
from pathlib import Path
from tkinter import messagebox, ttk

from . import paths
from .affixdb import AffixDb
from .bootstrap import ensure_once, last_report
from .config import ConfigError, EditorConfig, load_config
from .editor import (
    AccessoryView,
    SaveDescriptor,
    accessory_catalog_ids,
    apply_edits,
    commit_save,
    discover_saves,
    inspect_layout,
    list_accessories,
    list_backups,
    open_save,
    restore_backup,
    save_checksum_is_valid,
)
from .paths import resource_root
from .records import (
    EFFECT_COUNT,
    EMPTY_EFFECT_ID,
    EffectSlot,
    InventoryLayout,
    RecordError,
    describe_diagnosis,
    layout_diagnosis,
)
from .savefile import (
    SAVE_WRITE_REQUIREMENT,
    BackupEntry,
    SaveCrypto,
    SaveError,
    backup_directory_for,
    create_backup,
    running_game_processes,
    save_root_directory,
)
from .version import UNKNOWN, version_banner, version_info

DISCLAIMER = (
    "仅供测试学习用，不要用于联机影响游戏平衡。\n"
    "仁王3 为单机/纯 PVE 联机游戏，本工具不会影响其他玩家。"
)

#: One-line form of savefile.SAVE_WRITE_REQUIREMENT for the always-visible
#: status area; the full wording goes into the write-confirmation dialog.
WRITE_REQUIREMENT_SHORT = (
    "写入存档前请先退出游戏，或退回到游戏标题界面；在游戏内写入会被游戏下次保存覆盖。"
)

TITLE = "仁王3 饰品词条修改器（仅供测试学习用）"
SUBTITLE = "词条取自《仁王3词条装备库v2.21》 · 修改结果直接写回存档"
EMPTY_LABEL = "(空)"

#: Game-process state line.  Writing needs the game closed, so the state is shown
#: continuously instead of only when a write is refused.
GAME_STATUS_UNKNOWN = "游戏状态：检查中…"
GAME_STATUS_CLOSED = "游戏状态：未检测到仁王3 进程 —— 可以写入存档"
GAME_STATUS_RUNNING = (
    "游戏状态：{names} 正在运行 —— 写入会被拒绝，请完全退出游戏"
    "（或退回到标题界面且不加载存档）后重试"
)
#: How often the process list is re-checked (ms).  The check spawns tasklist, so
#: it runs on the worker thread and never blocks the window.
GAME_STATUS_INTERVAL_MS = 3000


class UiEditError(ValueError):
    """Raised when the current widget selection cannot be turned into an edit."""


def _load_image(path: Path, master: tk.Misc | None = None) -> tk.PhotoImage | None:
    """Load a PNG for the GUI, returning ``None`` when it is unavailable.

    The assets are generated by ``tools/make_icon.py`` and shipped next to the
    executable; a user who deletes them still gets a working window, just
    without the branding.  ``master`` must be passed when more than one Tk
    interpreter exists (a ``PhotoImage`` belongs to exactly one), which is why
    the application always passes itself.
    """
    try:
        if not path.is_file():
            return None
        return tk.PhotoImage(master=master, file=str(path))
    except Exception:  # noqa: BLE001 - cosmetic only, never break the window
        return None


class AccessoryEditorApp(tk.Tk):
    """Main window: save selection, record list, affix slots, write actions."""

    def __init__(self, config: EditorConfig | None = None) -> None:
        super().__init__()
        self.config = config if config is not None else load_config()
        self.state_root = self.config.resolved_backup_root()
        self.title(f"{TITLE} · v{version_info().version}")
        self.geometry("1000x700")
        self.minsize(880, 620)

        # Keep references: a PhotoImage that no widget holds is garbage collected
        # and the image silently disappears.
        self._images: dict[str, tk.PhotoImage] = {}
        self._apply_window_icon()

        self.affix_db = AffixDb()
        self._backend_note = ""
        self.crypto = self._build_crypto()
        self.saves: list[SaveDescriptor] = []
        self.accessory_views: list[AccessoryView] = []
        self.other_views: list[AccessoryView] = []
        # The array the listing came from: edits must reuse exactly this one.
        self.layout: InventoryLayout | None = None
        self.decrypted: bytes | None = None
        self.selected_save: SaveDescriptor | None = None
        self.selected_accessory: int | None = None
        self.checksum_ok = False
        self.worker_queue: queue.Queue[tuple[str, object]] = queue.Queue()
        self._game_status_at = 0.0

        self._build_ui()
        self.after(80, self._poll_worker)
        self.after(200, self._poll_game_status)
        self.refresh_saves()

    def _build_crypto(self) -> SaveCrypto:
        """Use the configured backend, degrading to pure Python when missing."""
        backend = self.config.crypto_backend()
        if backend.note:
            self._backend_note = backend.note
        return SaveCrypto(backend.executable, prefer_python=backend.prefer_python)

    # -------------------------------------------------------------- branding

    def _apply_window_icon(self) -> None:
        """Set the taskbar/title-bar icon from ``assets/app.ico``.

        ``iconbitmap`` gives Windows the full multi-resolution icon (so the
        taskbar picks a crisp size); ``iconphoto`` is the fallback for Tk builds
        that cannot read an ``.ico``.
        """
        icon = paths.icon_path()
        try:
            if icon.is_file():
                self.iconbitmap(default=str(icon))
                return
        except Exception:  # noqa: BLE001 - cosmetic only
            pass
        logo = _load_image(paths.logo_path(32), self)
        if logo is not None:
            self._images["window"] = logo
            try:
                self.iconphoto(True, logo)
            except Exception:  # noqa: BLE001 - cosmetic only
                pass

    def _header_logo(self) -> None:
        """Logo + wordmark row above the save selector."""
        header = ttk.Frame(self, padding=(8, 8, 8, 0))
        header.pack(fill=tk.X)

        logo = _load_image(paths.logo_path(64), self)
        if logo is not None:
            self._images["header"] = logo
            ttk.Label(header, image=logo).pack(side=tk.LEFT)
        else:
            ttk.Label(header, text="勾玉", font=("Yu Mincho", 20)).pack(side=tk.LEFT)

        text = ttk.Frame(header, padding=(10, 0, 0, 0))
        text.pack(side=tk.LEFT, fill=tk.X, expand=True)
        ttk.Label(text, text=TITLE, font=("Microsoft YaHei UI", 13, "bold"),
                  foreground="#1b2233").pack(anchor=tk.W)
        ttk.Label(text, text=SUBTITLE, foreground="#666666").pack(anchor=tk.W)

    # ------------------------------------------------------------------ UI

    def _build_ui(self) -> None:
        self._header_logo()

        top = ttk.Frame(self, padding=(8, 6))
        top.pack(side=tk.TOP, fill=tk.X)

        ttk.Label(top, text="存档:").pack(side=tk.LEFT)
        self.save_combo = ttk.Combobox(top, state="readonly", width=60)
        self.save_combo.pack(side=tk.LEFT, padx=4)
        self.save_combo.bind("<<ComboboxSelected>>", lambda _event: self._on_save_selected())
        ttk.Button(top, text="刷新", command=self.refresh_saves).pack(side=tk.LEFT, padx=2)
        ttk.Button(top, text="读取饰品", command=self.load_accessories).pack(side=tk.LEFT, padx=2)
        ttk.Button(top, text="备份存档", command=self.backup_save).pack(side=tk.LEFT, padx=2)
        ttk.Button(top, text="恢复备份", command=self.restore_save).pack(side=tk.LEFT, padx=2)

        # Everything below the record list is packed from the *bottom* edge, in
        # reverse visual order, before the expanding middle section.  pack()
        # hands out space in call order, so a bar packed with side=BOTTOM keeps
        # its height no matter how small the window is; previously a long status
        # text in the same row pushed 应用修改/写入存档 off the right edge and a
        # short window squeezed them to zero height.
        ttk.Label(self, text=DISCLAIMER, foreground="#b30000",
                  justify=tk.LEFT).pack(side=tk.BOTTOM, fill=tk.X, padx=8, pady=4)

        footer = ttk.Frame(self, padding=(8, 2))
        footer.pack(side=tk.BOTTOM, fill=tk.X)
        self.version_var = tk.StringVar(value=self._version_text())
        ttk.Label(footer, textvariable=self.version_var, foreground="#555555",
                  justify=tk.LEFT, font=("Consolas", 8)).pack(side=tk.LEFT)
        ttk.Button(footer, text="版本信息",
                   command=self.show_version_info).pack(side=tk.RIGHT, padx=4)

        ttk.Separator(self).pack(side=tk.BOTTOM, fill=tk.X)

        # Always visible (not only in the confirmation dialog): the write target
        # is the save on disk, so the game must not hold that save in memory.
        self.write_requirement_var = tk.StringVar(value=WRITE_REQUIREMENT_SHORT)
        ttk.Label(self, textvariable=self.write_requirement_var, foreground="#b03030",
                  wraplength=960, justify=tk.LEFT).pack(side=tk.BOTTOM, fill=tk.X,
                                                        padx=8, pady=(2, 0))

        # Live game-process state: the one condition that decides whether a write
        # is even allowed, so it is reported continuously instead of only after a
        # refused write.
        self.game_status_var = tk.StringVar(value=GAME_STATUS_UNKNOWN)
        self.game_status_label = ttk.Label(self, textvariable=self.game_status_var,
                                           foreground="#666666")
        self.game_status_label.pack(side=tk.BOTTOM, fill=tk.X, padx=8, pady=(2, 0))

        controls = ttk.Frame(self, padding=(8, 2))
        controls.pack(side=tk.BOTTOM, fill=tk.X)
        self.controls = controls
        self.dry_run_var = tk.BooleanVar(value=self.config.default_dry_run)
        ttk.Checkbutton(controls, text="仅演练（不写回）",
                        variable=self.dry_run_var).pack(side=tk.LEFT, padx=6)
        self.verify_var = tk.BooleanVar(value=self.config.default_verify)
        ttk.Checkbutton(controls, text="写入校验",
                        variable=self.verify_var).pack(side=tk.LEFT, padx=6)
        ttk.Button(controls, text="应用修改",
                   command=self.apply_edits_to_selection).pack(side=tk.LEFT, padx=2)
        self.write_button = ttk.Button(controls, text="写入存档", command=self.write_save)
        self.write_button.pack(side=tk.LEFT, padx=2)

        # Status line for the last action gets its own row (wrapping, so a long
        # message cannot displace any control) and the record-table detail goes to
        # a second, quieter row.
        self.status_var = tk.StringVar(
            value=self._backend_note if self._backend_note else "就绪"
        )
        self.status_label = ttk.Label(self, textvariable=self.status_var,
                                     foreground="#0366d6", wraplength=960,
                                     justify=tk.LEFT)
        self.status_label.pack(side=tk.BOTTOM, fill=tk.X, padx=8)
        self.table_var = tk.StringVar(value="")
        self.table_label = ttk.Label(self, textvariable=self.table_var,
                                     foreground="#666666", wraplength=960,
                                     justify=tk.LEFT)
        self.table_label.pack(side=tk.BOTTOM, fill=tk.X, padx=8)

        mid = ttk.Panedwindow(self, orient=tk.HORIZONTAL)
        mid.pack(side=tk.TOP, fill=tk.BOTH, expand=True, padx=8, pady=4)

        left = ttk.Frame(mid)
        ttk.Label(left, text="饰品记录（选择后编辑右侧词条槽）").pack(anchor=tk.W)
        self.tree = ttk.Treeview(
            left, columns=("level", "rarity", "type"), show="tree headings", height=16,
        )
        self.tree.heading("#0", text="记录")
        self.tree.heading("level", text="等级")
        self.tree.heading("rarity", text="品质")
        self.tree.heading("type", text="类型")
        self.tree.column("level", width=52, anchor=tk.CENTER)
        self.tree.column("rarity", width=76, anchor=tk.CENTER)
        self.tree.column("type", width=76, anchor=tk.CENTER)
        self.tree.pack(fill=tk.BOTH, expand=True)
        self.tree.bind("<<TreeviewSelect>>", lambda _event: self._on_accessory_selected())
        mid.add(left, weight=2)

        right = ttk.Frame(mid)
        ttk.Label(right, text="词条槽（选择词条后点 应用修改）").pack(anchor=tk.W)
        slot_frame = ttk.Frame(right)
        slot_frame.pack(fill=tk.BOTH, expand=True)
        self.slot_combos: list[ttk.Combobox] = []
        self.slot_labels: list[tk.StringVar] = []
        for index in range(EFFECT_COUNT):
            row = ttk.Frame(slot_frame)
            row.pack(fill=tk.X, pady=1)
            ttk.Label(row, text=f"槽{index + 1}:", width=5).pack(side=tk.LEFT)
            combo = ttk.Combobox(row, state="readonly", width=62,
                                 values=self.affix_db.labels())
            combo.pack(side=tk.LEFT, fill=tk.X, expand=True)
            combo.bind("<<ComboboxSelected>>",
                       lambda _event, slot=index: self._on_slot_picked(slot))
            self.slot_combos.append(combo)
            self.slot_labels.append(tk.StringVar(value=""))
            ttk.Label(row, textvariable=self.slot_labels[index],
                      foreground="#666666").pack(side=tk.LEFT)

        note = ttk.Label(
            right,
            text=("说明：词条选择来自《仁王3词条装备库v2.21》饰品词条表，"
                  "非表内词条一律拒绝。选择词条会写入该词条的 ID 与标称数值；"
                  "标识(metadata) 位不会被改写，因为其在存档中的编码尚未核实。\n"
                  "每件饰品的最后一个词条是「恩宠/套装组合」词条（如 稻荷神的恩宠），"
                  "它不在饰品词条表内，因此显示为表外词条；给该槽选择表内词条会把它替换掉。"),
            foreground="#666666", wraplength=520, justify=tk.LEFT,
        )
        note.pack(anchor=tk.W, pady=(6, 0))
        mid.add(right, weight=3)

    # ------------------------------------------------------------- version

    @staticmethod
    def _version_text() -> str:
        """Four required facts: commit tail, source, build time, language."""
        info = version_info()
        built = info.built_at if info.built_at != UNKNOWN else "未构建（源码运行）"
        return (
            f"版本 v{info.version} · commit {info.commit}{info.dirty_suffix}\n"
            f"来源 {info.built_from}\n"
            f"加密组件 {info.crypto_exe}\n"
            f"构建时间 {built} · 语言 {info.language}"
        )

    def show_version_info(self) -> None:
        info = version_info()
        details = [version_banner(info), ""]
        if info.commit_full not in ("", UNKNOWN):
            details.append(f"完整 commit: {info.commit_full}")
        details.append(f"分支       : {info.branch}")
        if info.crypto_exe_sha256 not in ("", UNKNOWN):
            details.append(f"组件 SHA-256: {info.crypto_exe_sha256}")
        details.append(f"信息来源   : {info.source}")
        details.append("")
        details.append(f"程序目录   : {resource_root()}")
        details.append(f"配置文件   : {self.config.source or paths.default_config_path()}")
        details.append(f"备份目录   : {self.state_root}")
        if self._backend_note:
            details.append(f"加密后端   : {self._backend_note}")
        report = last_report()
        if report is not None:
            details.append(f"随附文件   : {report.summary()}")
        messagebox.showinfo("版本信息", "\n".join(details))

    # ------------------------------------------------------------- helpers

    def _status(self, text: str) -> None:
        self.status_var.set(text)

    def _poll_game_status(self) -> None:
        """Refresh the game-process line, off the UI thread and rate-limited.

        The check spawns ``tasklist``, so it must not run on the UI thread, and it
        must not touch the status line (that one reports the user's own actions).
        """
        now = time.monotonic()
        if now - self._game_status_at >= GAME_STATUS_INTERVAL_MS / 1000:
            self._game_status_at = now
            self._run_background(self._check_game_status)
        self.after(GAME_STATUS_INTERVAL_MS, self._poll_game_status)

    def _check_game_status(self) -> tuple[str, tuple[str, ...]]:
        return "game_status", tuple(running_game_processes())

    def _show_game_status(self, running: object) -> None:
        names = tuple(str(name) for name in running) if running else ()
        if names:
            self.game_status_var.set(GAME_STATUS_RUNNING.format(names="、".join(names)))
            self.game_status_label.configure(foreground="#b03030")
        else:
            self.game_status_var.set(GAME_STATUS_CLOSED)
            self.game_status_label.configure(foreground="#1a7f37")

    def _run_background(self, function, *args) -> None:
        """Run ``function`` off the UI thread and deliver its result to the queue."""
        def runner() -> None:
            try:
                self.worker_queue.put(("ok", function(*args)))
            except Exception as error:  # noqa: BLE001 - surfaced through the GUI
                self.worker_queue.put(("error", error))

        threading.Thread(target=runner, daemon=True).start()

    def _run_worker(self, function, *args) -> None:
        self._run_background(function, *args)
        self._status("处理中…")

    def _poll_worker(self) -> None:
        try:
            while True:
                kind, payload = self.worker_queue.get_nowait()
                if kind == "ok":
                    self._on_worker_ok(payload)
                else:
                    self._on_worker_error(payload)
        except queue.Empty:
            pass
        self.after(80, self._poll_worker)

    def _on_worker_ok(self, payload: object) -> None:
        if not isinstance(payload, tuple) or not payload:
            return
        tag, value = payload[0], payload[1] if len(payload) > 1 else None
        if tag == "saves":
            self._populate_saves(value)
        elif tag == "accessories":
            self._populate_accessories(value)
        elif tag == "accessories_failed":
            self._report_no_layout(value)
        elif tag == "written" and isinstance(value, dict):
            self._status(f"已写入，SHA-256 {value.get('new_sha256', '')}")
            messagebox.showinfo("完成", "修改已写入存档。\n请在游戏中重新加载存档查看效果。")
        elif tag == "dry_run" and isinstance(value, dict):
            self._status("演练完成（未写入）")
            messagebox.showinfo(
                "演练结果",
                "未写入任何文件。\n\n"
                f"校验和 {value.get('checksum_before')} -> {value.get('checksum_after')}",
            )
        elif tag == "backup" and isinstance(value, str):
            self._status(f"备份完成：{value}")
            messagebox.showinfo("备份完成", f"已备份到：\n{value}")
        elif tag == "restored" and isinstance(value, dict):
            self._status(f"已恢复备份，SHA-256 {value.get('new_sha256', '')}")
            matches = value.get("matches_original_save")
            note = ""
            if matches is True:
                note = "\n\n校验：与备份时记录的原文件 SHA-256 完全一致。"
            elif matches is False:
                note = ("\n\n注意：与备份时记录的原文件 SHA-256 不一致"
                        "（可能仅存档尾 8 字节不同）。")
            messagebox.showinfo(
                "恢复完成",
                f"已用备份覆盖存档：\n{value.get('restored_from')}\n\n"
                f"恢复前的存档已另存到：\n{value.get('safety_backup_dir')}"
                + note + "\n\n请在游戏中加载该存档确认。",
            )
            self._invalidate_loaded_save()
        elif tag == "restore_dry_run" and isinstance(value, dict):
            self._status("恢复演练完成（未写入）")
            messagebox.showinfo(
                "恢复演练",
                "未写入任何文件。\n\n"
                f"将恢复自：{value.get('restored_from')}",
            )
        elif tag == "game_status":
            self._show_game_status(value)

    def _invalidate_loaded_save(self) -> None:
        """The file changed underneath us: force a re-read before any write."""
        self.decrypted = None
        self.accessory_views = []
        self.other_views = []
        self.layout = None
        self.selected_accessory = None
        self.checksum_ok = False
        self.tree.delete(*self.tree.get_children())
        for combo in self.slot_combos:
            combo.set("")
        for label in self.slot_labels:
            label.set("")

    def _on_worker_error(self, error: Exception) -> None:
        self._status("操作失败")
        messagebox.showerror("错误", str(error))

    # ------------------------------------------------------------- actions

    def refresh_saves(self) -> None:
        self._run_worker(self._load_saves)

    def _load_saves(self) -> tuple[str, tuple[SaveDescriptor, ...]]:
        """Scan the configured save root (an instance method: it reads config)."""
        return "saves", discover_saves(self.config.resolved_save_root())

    def _populate_saves(self, saves: object) -> None:
        self.saves = list(saves) if saves else []
        self.save_combo["values"] = [save.display for save in self.saves]
        if self.saves:
            self.save_combo.current(0)
            self.selected_save = self.saves[0]
            self._status(f"发现 {len(self.saves)} 个存档")
            self.table_var.set("")
        else:
            self.selected_save = None
            self._status("未发现存档")
            self.table_var.set(f"查找位置 {self._search_root_hint()}")

    def _search_root_hint(self) -> Path:
        """Where the scan looked, so an empty list is actionable."""
        configured = self.config.resolved_save_root()
        return Path(configured) if configured else save_root_directory()

    def _on_save_selected(self) -> None:
        index = self.save_combo.current()
        if 0 <= index < len(self.saves):
            self.selected_save = self.saves[index]
            self._status(f"已选择 {self.saves[index].display}")

    def load_accessories(self) -> None:
        if self.selected_save is None:
            messagebox.showwarning("提示", "请先选择存档")
            return
        self._run_worker(self._load_accessories_worker, self.selected_save)

    def _load_accessories_worker(self, save: SaveDescriptor) -> tuple[str, tuple]:
        data = open_save(save, self.crypto)
        checksum_ok = save_checksum_is_valid(data)
        known_ids = accessory_catalog_ids(self.affix_db)
        try:
            layout = inspect_layout(data, known_ids=known_ids)
        except RecordError as error:
            # No array at all: report the diagnosis instead of a silent empty
            # table, so the user can send it back and the layout can be fixed.
            return "accessories_failed", (data, checksum_ok, str(error),
                                          layout_diagnosis(data))
        views = list_accessories(data, layout=layout, known_ids=known_ids)
        return "accessories", (data, views, checksum_ok, layout)

    def _populate_accessories(self, payload: object, *, keep_selection: bool = False) -> None:
        data, views, checksum_ok, layout = payload
        self.decrypted = data
        self.checksum_ok = bool(checksum_ok)
        self.layout = layout
        # Only records whose affixes really are 饰品词条 are editable accessories;
        # weapons/armour/绘卷 share the same array and are reported separately.
        # ``is_accessory is None`` means no catalog evidence was supplied, so the
        # record is kept (that is the legacy behaviour) instead of being dropped.
        self.accessory_views = [view for view in views if view.is_accessory is not False]
        self.other_views = [view for view in views if view.is_accessory is False]
        # Clearing a record's last 饰品词条 would otherwise make it drop out of the
        # list while the user is still editing it, so the record being edited is
        # always kept visible.
        if keep_selection and self.selected_accessory is not None:
            listed = {view.slot_index for view in self.accessory_views}
            retained = next((view for view in views
                             if view.slot_index == self.selected_accessory
                             and view.slot_index not in listed), None)
            if retained is not None:
                self.accessory_views.append(retained)
        self.tree.delete(*self.tree.get_children())
        for view in self.accessory_views:
            label = f"{view.kind_name} {view.record_type:#06x}"
            if view.catalog_hits is not None:
                label += f" 词条命中 {view.catalog_hits}"
            self.tree.insert(
                "", "end", iid=str(view.slot_index),
                text=f"#{view.slot_index} @ {view.offset:#x}",
                values=(view.level, view.rarity_name, label),
            )
        known = {view.slot_index for view in self.accessory_views}
        if not keep_selection or self.selected_accessory not in known:
            self.selected_accessory = None
        for index in range(EFFECT_COUNT):
            self.slot_combos[index].set("")
            self.slot_labels[index].set("")
        suffix = "" if self.checksum_ok else "（校验和不一致，请谨慎）"
        others = len(self.other_views)
        other_note = f" · 另有 {others} 条武器/防具/绘卷记录未列出" if others else ""
        if not self.accessory_views:
            self._status(f"记录表里没有含饰品词条的记录{suffix}")
            self.table_var.set(layout.describe())
            messagebox.showinfo(
                "未找到饰品记录",
                "已在存档中找到记录表，但其中没有含饰品词条（词条 id 命中饰品词条库）"
                "的记录。\n\n"
                + layout.describe()
                + f"\n\n记录表内共 {len(views)} 条物品记录，均未命中饰品词条库，"
                  "可能都是武器/防具/绘卷。\n\n"
                  "提示：读取存档文件即可，游戏无需运行。\n"
                  "可在命令行运行 scan 命令查看完整诊断并反馈给作者。",
            )
            return
        self._status(f"已读取 {len(self.accessory_views)} 件饰品{suffix}{other_note}")
        self.table_var.set(layout.describe())

    def _report_no_layout(self, payload: object) -> None:
        """Show why nothing could be read, with the raw diagnosis."""
        _data, checksum_ok, message, diagnosis = payload
        self.accessory_views = []
        self.other_views = []
        self.layout = None
        self.selected_accessory = None
        self.tree.delete(*self.tree.get_children())
        for index in range(EFFECT_COUNT):
            self.slot_combos[index].set("")
            self.slot_labels[index].set("")
        suffix = "" if checksum_ok else "（校验和不一致，请谨慎）"
        self._status(f"未能定位物品记录表{suffix}")
        self.table_var.set("\n".join(describe_diagnosis(diagnosis)))
        messagebox.showwarning(
            "未能定位物品记录表",
            f"{message}\n\n"
            + "\n".join(describe_diagnosis(diagnosis))
            + "\n\n提示：读取存档文件即可，游戏无需运行。\n"
              "请把以上诊断（或用 scan --json 的输出）反馈给作者。",
        )

    def _selected_view(self) -> AccessoryView | None:
        return next(
            (item for item in self.accessory_views
             if item.slot_index == self.selected_accessory),
            None,
        )

    def _on_accessory_selected(self) -> None:
        selection = self.tree.selection()
        if not selection:
            return
        self.selected_accessory = int(selection[0])
        view = self._selected_view()
        if view is None:
            return
        grace = view.grace_slots(self.affix_db)
        for index, effect in enumerate(view.effects):
            if effect.is_empty:
                self.slot_combos[index].set(EMPTY_LABEL)
                self.slot_labels[index].set("")
                continue
            entry = self.affix_db.lookup(effect.effect_id)
            if index in grace:
                # 恩宠 / 套装组合 effect: not in the shipped 饰品词条 table, so it
                # is reported by name instead of as an unexplained unknown id.
                label = f"{effect.effect_id:#06x} 恩宠/套装词条（表外）"
                detail = (f"数值={effect.value} 标识={effect.metadata:#010x}"
                          " ← 改选表内词条会把它替换掉")
            else:
                label = entry.label if entry else f"{effect.effect_id:#06x} (非表内词条)"
                detail = f"数值={effect.value} 标识={effect.metadata:#010x}"
            self.slot_combos[index].set(label)
            self.slot_labels[index].set(detail)

    def _on_slot_picked(self, index: int) -> None:
        text = self.slot_combos[index].get()
        self.slot_labels[index].set("" if text == EMPTY_LABEL else text)

    def _pending_edit(self, index: int, current: EffectSlot) -> dict[str, int] | None:
        """Turn one slot widget into an edit, or ``None`` when nothing changed.

        Picking a legal affix writes the affix's 词条代码 into the slot: its
        effect id plus the catalog's nominal value (both live at the same
        relative offsets in the code and in the slot).  ``metadata`` is left
        untouched on purpose -- the slot-level encoding of the 固定/星 flag bits
        is not confirmed against a real save, so the GUI never guesses at it
        (the CLI can still set it explicitly with ``--edit slot:id:value:meta``).
        """
        text = self.slot_combos[index].get()
        if not text:
            return None
        if text == EMPTY_LABEL:
            if current.is_empty:
                return None
            return {"slot_index": index, "effect_id": EMPTY_EFFECT_ID}
        try:
            effect_id = int(text.split(" ", 1)[0], 16)
        except ValueError as error:
            raise UiEditError(f"无法解析词条选择：{text!r}") from error
        if effect_id == current.effect_id:
            return None  # unchanged: leave value/metadata untouched
        entry = self.affix_db.lookup(effect_id)
        if entry is None:
            raise UiEditError(f"词条 {effect_id:#06x} 不在合法的饰品词条表中")
        return {
            "slot_index": index,
            "effect_id": effect_id,
            "value": entry.value,
        }

    def _current_edits(self) -> tuple[dict[str, int], ...]:
        """Collect the changed slots for the selected accessory record."""
        if self.selected_accessory is None:
            return ()
        view = self._selected_view()
        if view is None:
            return ()
        edits: list[dict[str, int]] = []
        for index in range(EFFECT_COUNT):
            try:
                edit = self._pending_edit(index, view.effects[index])
            except UiEditError as error:
                messagebox.showwarning("提示", str(error))
                return ()
            if edit is not None:
                edits.append(dict(edit, record_index=self.selected_accessory))
        return tuple(edits)

    def apply_edits_to_selection(self) -> None:
        if self.decrypted is None or self.selected_accessory is None:
            messagebox.showwarning("提示", "请先读取饰品并选择一条记录")
            return
        target = self.selected_accessory
        edits = self._current_edits()
        if not edits:
            messagebox.showwarning("提示", "当前没有检测到改动")
            return
        known_ids = accessory_catalog_ids(self.affix_db)
        try:
            # Same catalog evidence and same located array as the listing, so a
            # record index cannot resolve to a different item while editing.
            self.decrypted = apply_edits(self.decrypted, edits,
                                         affix_db=self.affix_db,
                                         known_ids=known_ids,
                                         layout=self.layout)
        except Exception as error:  # noqa: BLE001 - surfaced through the GUI
            messagebox.showerror("错误", str(error))
            return
        # Refresh the tree from the patched memory image so the display matches
        # exactly what a write would persist.  The on-disk checksum is stale by
        # definition until commit, so keep the checksum verdict from load time.
        layout = inspect_layout(self.decrypted, known_ids=known_ids)
        self._populate_accessories(
            (self.decrypted,
             list_accessories(self.decrypted, layout=layout, known_ids=known_ids),
             self.checksum_ok, layout),
            keep_selection=True,
        )
        # Restore the selection explicitly: <<TreeviewSelect>> is not guaranteed
        # to fire synchronously, and the slot widgets must mirror the new state.
        self.tree.selection_set(str(target))
        self.selected_accessory = target
        self._on_accessory_selected()
        self._status(f"记录 #{target} 的修改已应用到内存数据（尚未写入存档）")

    def backup_save(self) -> None:
        if self.selected_save is None:
            messagebox.showwarning("提示", "请先选择存档")
            return
        save = self.selected_save
        crypto = self.crypto

        def worker() -> tuple[str, str]:
            return "backup", str(create_backup(save.path, state_root=self.state_root,
                                               crypto=crypto))

        self._run_worker(worker)

    # ------------------------------------------------------------- restore

    def restore_save(self) -> None:
        """Pick a plaintext backup and put it back into the save file."""
        if self.selected_save is None:
            messagebox.showwarning("提示", "请先选择存档")
            return
        save = self.selected_save
        try:
            entries = list_backups(save.path, self.state_root)
        except (SaveError, ValueError) as error:
            messagebox.showinfo(
                "无法定位备份目录",
                f"该存档路径无法对应到备份目录：\n{save.path}\n\n{error}",
            )
            return
        if not entries:
            messagebox.showinfo(
                "没有可用备份",
                "该存档还没有备份。\n\n"
                f"备份目录：\n{self._backup_directory_hint(save.path)}\n\n"
                "写入存档前会自动备份，也可以用「备份存档」先手动备份一份。",
            )
            return
        chosen = self._choose_backup_dialog(entries)
        if chosen is None:
            return
        self._restore_selected_backup(save, chosen)

    def _backup_directory_hint(self, save_path: Path) -> str:
        """The backup directory for a save, or an explanation when unknowable.

        The path shape (``<state root>/account-<id>/slot-<NN>``) needs the Steam
        account id from the save path, which a hand-copied file elsewhere on disk
        does not carry.
        """
        try:
            return str(backup_directory_for(save_path, self.state_root))
        except (SaveError, ValueError):
            return ("（无法从该路径识别账号/栏位；可在 config/editor.json 中"
                    "用 backup_root 指定备份目录）")

    def _choose_backup_dialog(self, entries: tuple[BackupEntry, ...]) -> BackupEntry | None:
        """Modal list of backups (newest first); returns the picked entry."""
        dialog = tk.Toplevel(self)
        dialog.title("选择要恢复的备份")
        dialog.transient(self)
        dialog.geometry("720x360")
        ttk.Label(
            dialog,
            text=("选择一个备份恢复。备份是解密后的明文，恢复时会重新加密写回存档；\n"
                  "恢复前会自动把当前存档另存一份，因此恢复本身也可以撤销。"),
            justify=tk.LEFT,
        ).pack(anchor=tk.W, padx=10, pady=(10, 4))

        frame = ttk.Frame(dialog)
        frame.pack(fill=tk.BOTH, expand=True, padx=10)
        listbox = tk.Listbox(frame, height=10, activestyle="dotbox")
        scrollbar = ttk.Scrollbar(frame, orient=tk.VERTICAL, command=listbox.yview)
        listbox.configure(yscrollcommand=scrollbar.set)
        listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        for index, entry in enumerate(entries, start=1):
            note = "" if entry.integrity_ok else "  ⚠ 校验不符"
            listbox.insert(tk.END, f"{index:>3}. {entry.when}   "
                                   f"{entry.plain_size / 1024 / 1024:.1f} MB{note}")
        listbox.selection_set(0)
        listbox.see(0)

        ttk.Label(dialog, text=f"备份目录：{entries[0].plain_path.parent}",
                  foreground="#666666", wraplength=680,
                  justify=tk.LEFT).pack(anchor=tk.W, padx=10, pady=(4, 0))
        chosen: list[BackupEntry] = []

        def accept() -> None:
            selection = listbox.curselection()
            if not selection:
                return
            chosen.append(entries[selection[0]])
            dialog.destroy()

        buttons = ttk.Frame(dialog, padding=(10, 8))
        buttons.pack(fill=tk.X)
        ttk.Button(buttons, text="恢复此备份", command=accept).pack(side=tk.RIGHT)
        ttk.Button(buttons, text="取消", command=dialog.destroy).pack(side=tk.RIGHT, padx=6)
        listbox.bind("<Double-Button-1>", lambda _event: accept())
        dialog.protocol("WM_DELETE_WINDOW", dialog.destroy)

        dialog.grab_set()
        self.wait_window(dialog)
        return chosen[0] if chosen else None

    def _restore_selected_backup(self, save: SaveDescriptor, entry: BackupEntry) -> None:
        running = running_game_processes()
        warning = ""
        if entry.slot_index is not None and entry.slot_index != save.slot_index:
            warning += (f"\n\n⚠ 该备份来自栏位 {entry.slot_index:02d}，"
                        f"当前存档是栏位 {save.slot_index:02d}——请确认内容无误。")
        if running:
            warning += ("\n\n⚠ 检测到游戏正在运行（" + "、".join(running) + "）。\n"
                        "若你正处于游戏内的存档中，恢复的内容会被游戏下次保存覆盖。")
        if not messagebox.askyesno(
            "确认恢复",
            f"将用以下备份覆盖当前存档：\n{entry.plain_path}\n"
            f"备份时间：{entry.when}\n\n"
            + SAVE_WRITE_REQUIREMENT + "\n\n"
            "（当前存档会先自动备份一份，可再恢复回来。）\n\n"
            + DISCLAIMER + warning + "\n\n确认继续吗？",
        ):
            return

        dry_run = bool(self.dry_run_var.get())
        verify = bool(self.verify_var.get())
        crypto = self.crypto

        def worker() -> tuple[str, dict]:
            result = restore_backup(
                save, entry, crypto=crypto, state_root=self.state_root,
                dry_run=dry_run, verify=verify, allow_game_running=True,
            )
            return ("restore_dry_run" if result.get("dry_run") else "restored"), result

        self._run_worker(worker)

    def write_save(self) -> None:
        if self.decrypted is None or self.selected_save is None:
            messagebox.showwarning("提示", "请先读取饰品")
            return
        running = running_game_processes()
        warning = ""
        if running:
            warning = (
                "\n\n⚠ 检测到游戏正在运行（" + "、".join(running) + "）。\n"
                "若你正处于游戏内的存档中，写进去的修改会被游戏下次保存覆盖。\n"
                "正确做法：完全退出游戏，或退回到标题界面后再写入。"
            )
            if not messagebox.askyesno(
                "游戏正在运行",
                "当前游戏正在运行，只有在【标题界面】写入才是安全的。\n"
                "确定你现在不在游戏内的存档中吗？" + warning,
            ):
                return
        if not messagebox.askyesno(
            "确认写入",
            "即将把修改写入存档（会自动备份原存档）。\n\n"
            + SAVE_WRITE_REQUIREMENT + "\n\n"
            + DISCLAIMER + warning + "\n\n确认继续吗？",
        ):
            return

        dry_run = bool(self.dry_run_var.get())
        verify = bool(self.verify_var.get())
        save = self.selected_save
        data = self.decrypted
        crypto = self.crypto

        def worker() -> tuple[str, dict]:
            result = commit_save(
                save, data, crypto=crypto, state_root=self.state_root,
                dry_run=dry_run, verify=verify, allow_game_running=True,
            )
            return ("dry_run" if result.get("dry_run") else "written"), result

        self._run_worker(worker)


def _hide_own_console() -> None:
    """Hide the console a double-clicked frozen build starts with.

    A console-subsystem executable gets a console window whether or not it was
    started from a terminal.  The window is hidden only when this process is the
    sole owner of that console, so running ``Nioh3AccessoryEditor.exe`` from an
    existing shell never hides the user's own terminal.  Best effort by design:
    a failure here must not stop the GUI from opening.
    """
    if not paths.is_frozen() or os.name != "nt":
        return
    try:
        import ctypes  # noqa: PLC0415 - Windows-only, imported on demand

        kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
        process_ids = (ctypes.c_ulong * 4)()
        attached = kernel32.GetConsoleProcessList(process_ids, 4)
        if attached <= 1:
            window = kernel32.GetConsoleWindow()
            if window:
                ctypes.WinDLL("user32", use_last_error=True).ShowWindow(window, 0)
    except Exception:  # noqa: BLE001 - cosmetic only
        return


def main(config: EditorConfig | None = None) -> int:
    if config is None:
        try:
            config = load_config()
        except ConfigError as error:
            messagebox.showerror("配置文件错误", str(error))
            return 2
    _hide_own_console()
    app = AccessoryEditorApp(config)
    app.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
