# -*- coding: utf-8 -*-
"""Generate the build/version artifacts for Nioh3AccessoryEditor.

``build.ps1`` calls this so that every version surface reports the same four
facts: the commit id tail (last 8 characters), where the build came from (the
project root plus the crypto executable it uses), the build timestamp, and the
programming language/runtime.

Outputs (all paths overridable, all created atomically):

* ``nioh3_accessory_editor/_buildinfo.py`` -- frozen facts imported at runtime
  by :mod:`nioh3_accessory_editor.version`; makes a copied/distributed tree
  report its real build identity even without ``.git``.
* ``BUILD-INFO.json`` -- machine-readable record (same schema as the rest of
  the project's build metadata).
* ``BUILD-INFO.txt`` -- the human-readable banner.

Run it directly (``python tools/make_build_info.py``) to refresh the build
identity of the working tree, or let ``build.ps1`` drive it.
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import platform
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:  # allow "python tools/make_build_info.py"
    sys.path.insert(0, str(PROJECT_ROOT))

from nioh3_accessory_editor.version import (  # noqa: E402  (path bootstrap)
    BUILD_SCHEMA,
    DEFAULT_CRYPTO_EXE,
    BuildInfo,
    UNKNOWN,
    __version__,
    short_commit,
)

MODULE_NAME = "_buildinfo"
DEFAULT_MODULE_PATH = PROJECT_ROOT / "nioh3_accessory_editor" / f"{MODULE_NAME}.py"
JSON_FILENAME = "BUILD-INFO.json"
TEXT_FILENAME = "BUILD-INFO.txt"

MODULE_TEMPLATE = '''# -*- coding: utf-8 -*-
"""Frozen build identity -- GENERATED by tools/make_build_info.py; do not edit.

Regenerate with ``python tools/make_build_info.py`` or ``build.ps1``.
"""

BUILD_SCHEMA = {schema!r}
VERSION = {version!r}
COMMIT = {commit!r}                 # last {commit_length} characters of COMMIT_FULL
COMMIT_FULL = {commit_full!r}
BRANCH = {branch!r}
DIRTY = {dirty!r}
BUILT_AT = {built_at!r}
BUILT_FROM = {built_from!r}
CRYPTO_EXE = {crypto_exe!r}
CRYPTO_EXE_SHA256 = {crypto_exe_sha256!r}
LANGUAGE = {language!r}
PYTHON_VERSION = {python_version!r}
'''


def sha256_of(path: Path) -> str:
    """Return the SHA-256 of ``path``, or ``unknown`` when unreadable."""
    try:
        digest = hashlib.sha256()
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1 << 20), b""):
                digest.update(chunk)
    except OSError:
        return UNKNOWN
    return digest.hexdigest()


def detect_language() -> str:
    """Describe the language/runtime this build targets."""
    implementation = platform.python_implementation()
    version = platform.python_version()
    details = ["仅标准库 / stdlib only"]
    try:
        import tkinter  # noqa: F401  (probe only)
    except Exception:  # noqa: BLE001 - tkinter is optional for the CLI
        details.append("无 tkinter")
    else:
        details.append("含 tkinter GUI")
    return f"{implementation} {version} ({', '.join(details)})"


def _git(arguments: list[str]) -> str | None:
    import subprocess

    try:
        result = subprocess.run(
            ["git", *arguments], cwd=str(PROJECT_ROOT),
            capture_output=True, text=True, timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def local_timestamp() -> str:
    """Local build time as ISO-8601 with the UTC offset (seconds precision)."""
    return datetime.datetime.now().astimezone().replace(microsecond=0).isoformat()


def collect(commit: str | None = None,
            branch: str | None = None,
            dirty: bool | None = None,
            crypto_exe: Path | None = None,
            built_from: Path | None = None,
            built_at: str | None = None,
            language: str | None = None) -> BuildInfo:
    """Resolve every fact, filling gaps from git / the environment."""
    commit_full = commit or _git(["rev-parse", "HEAD"]) or UNKNOWN
    if branch is None:
        branch = _git(["rev-parse", "--abbrev-ref", "HEAD"]) or UNKNOWN
    if dirty is None:
        status = _git(["status", "--porcelain"])
        dirty = bool(status) if status is not None else False

    exe = Path(crypto_exe) if crypto_exe else DEFAULT_CRYPTO_EXE
    return BuildInfo(
        version=__version__,
        commit=short_commit(commit_full),
        commit_full=commit_full,
        branch=branch,
        dirty=bool(dirty),
        built_at=built_at or local_timestamp(),
        built_from=str(Path(built_from).resolve()) if built_from else str(PROJECT_ROOT),
        crypto_exe=str(exe),
        crypto_exe_sha256=sha256_of(exe),
        language=language or detect_language(),
        python_version=platform.python_version(),
        source="build",
    )


def render_module(info: BuildInfo) -> str:
    return MODULE_TEMPLATE.format(
        schema=BUILD_SCHEMA,
        version=info.version,
        commit=info.commit,
        commit_length=len(info.commit),
        commit_full=info.commit_full,
        branch=info.branch,
        dirty=info.dirty,
        built_at=info.built_at,
        built_from=info.built_from,
        crypto_exe=info.crypto_exe,
        crypto_exe_sha256=info.crypto_exe_sha256,
        language=info.language,
        python_version=info.python_version,
    )


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(text, encoding="utf-8", newline="\n")
    temporary.replace(path)


def write_artifacts(info: BuildInfo, *, module_path: Path, out_dir: Path,
                    banner: str) -> dict[str, Path]:
    """Write the module, the JSON record and the text report."""
    written = {
        "module": module_path,
        "json": out_dir / JSON_FILENAME,
        "text": out_dir / TEXT_FILENAME,
    }
    _write_text(module_path, render_module(info))
    _write_text(written["json"],
                json.dumps(info.as_dict(), indent=2, ensure_ascii=False) + "\n")
    # 构建时所在的目录只写进这份报告（内部诊断用）：它是构建机的路径，对使用者
    # 没有意义，所以横幅 / 界面 / --version 都不显示它（见 version_lines 的说明）。
    _write_text(written["text"],
                banner + "\n" + f"构建来源  : {info.built_from}\n")
    return written


def verify_module(module_path: Path, info: BuildInfo) -> None:
    """Import the generated module and assert it reproduces every fact.

    Guards against template drift: if the generated file cannot reproduce the
    information the application reports, the build must fail loudly instead of
    shipping a tree that displays the wrong version.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location("_buildinfo_check", module_path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise RuntimeError(f"无法加载生成的文件: {module_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    expected = {
        "BUILD_SCHEMA": info.build_schema,
        "VERSION": info.version,
        "COMMIT": info.commit,
        "COMMIT_FULL": info.commit_full,
        "BRANCH": info.branch,
        "DIRTY": info.dirty,
        "BUILT_AT": info.built_at,
        "BUILT_FROM": info.built_from,
        "CRYPTO_EXE": info.crypto_exe,
        "CRYPTO_EXE_SHA256": info.crypto_exe_sha256,
        "LANGUAGE": info.language,
        "PYTHON_VERSION": info.python_version,
    }
    for name, value in expected.items():
        actual = getattr(module, name, None)
        if actual != value:
            raise RuntimeError(
                f"{module_path.name} 的 {name} 不一致: {actual!r} != {value!r}"
            )
    # Project rule: the short commit is the LAST 8 characters of the id.  A
    # tree without git metadata is tolerated, but a real id must shorten to 8.
    if info.commit_full != UNKNOWN and len(info.commit_full) >= 8:
        if len(info.commit) != 8:
            raise RuntimeError(
                f"commit 短号应为 commit id 后 8 位，实际 {info.commit!r}"
            )
        if not info.commit_full.endswith(info.commit):
            raise RuntimeError(
                f"commit 短号 {info.commit!r} 不是 {info.commit_full!r} 的后 8 位"
            )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="make_build_info.py",
        description="生成构建/版本信息（commit 后8位、来源、构建时间、语言）。",
    )
    parser.add_argument("--commit", help="完整 commit id（缺省从 git 读取）")
    parser.add_argument("--branch", help="分支名（缺省从 git 读取）")
    dirty = parser.add_mutually_exclusive_group()
    dirty.add_argument("--dirty", dest="dirty", action="store_true",
                       default=None, help="标记工作区有未提交改动")
    dirty.add_argument("--clean", dest="dirty", action="store_false",
                       help="标记工作区干净")
    parser.add_argument("--crypto-exe", type=Path, default=None,
                        help=f"加密组件路径（缺省 {DEFAULT_CRYPTO_EXE.name}）")
    parser.add_argument("--built-from", type=Path, default=None,
                        help="构建来源目录（缺省项目根目录）")
    parser.add_argument("--built-at", default=None, help="构建时间（ISO-8601）")
    parser.add_argument("--language", default=None, help="语言/运行时描述")
    parser.add_argument("--module-path", type=Path, default=DEFAULT_MODULE_PATH,
                        help="生成的 _buildinfo.py 路径")
    parser.add_argument("--out-dir", type=Path, default=PROJECT_ROOT,
                        help="BUILD-INFO.json/.txt 输出目录")
    parser.add_argument("--quiet", action="store_true", help="只打印文件路径")
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    info = collect(
        commit=arguments.commit,
        branch=arguments.branch,
        dirty=arguments.dirty,
        crypto_exe=arguments.crypto_exe,
        built_from=arguments.built_from,
        built_at=arguments.built_at,
        language=arguments.language,
    )
    if info.crypto_exe_sha256 == UNKNOWN:
        print(f"警告: 找不到加密组件 {info.crypto_exe}，其校验和记为 unknown",
              file=sys.stderr)

    from nioh3_accessory_editor.version import version_banner

    banner = version_banner(info)
    written = write_artifacts(info, module_path=arguments.module_path,
                              out_dir=arguments.out_dir, banner=banner)
    # The generated module must reproduce the banner the app renders.
    verify_module(written["module"], info)
    if arguments.quiet:
        for path in written.values():
            print(path)
    else:
        print(banner)
        print()
        for label, path in written.items():
            print(f"{label:>7}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
